// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  source: __t.string(),
  destination: __t.string(),
  sourcePort: __t.u16().name("source_port"),
  destinationPort: __t.u16().name("destination_port"),
  addressFamily: __t.u8().name("address_family"),
  state: __t.string(),
  packets: __t.u64(),
  bytes: __t.u64(),
  lastSequence: __t.u32().name("last_sequence"),
  lastAcknowledgment: __t.u32().name("last_acknowledgment"),
  lastSeen: __t.timestamp().name("last_seen"),
  active: __t.bool(),
});
