// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  address: __t.string(),
  port: __t.u16(),
  addressFamily: __t.u8().name("address_family"),
  firstSeen: __t.timestamp().name("first_seen"),
  lastSeen: __t.timestamp().name("last_seen"),
  packetsSent: __t.u64().name("packets_sent"),
  packetsReceived: __t.u64().name("packets_received"),
  bytesSent: __t.u64().name("bytes_sent"),
  bytesReceived: __t.u64().name("bytes_received"),
  active: __t.bool(),
});
