// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  captureId: __t.string(),
  direction: __t.string(),
  source: __t.string(),
  destination: __t.string(),
  sourcePort: __t.u16(),
  destinationPort: __t.u16(),
  addressFamily: __t.u8(),
  flags: __t.string(),
  sequence: __t.u32(),
  acknowledgment: __t.u32(),
  window: __t.u32(),
  payloadLength: __t.u32(),
};
