// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  captureId: __t.string().name("capture_id"),
  connectionId: __t.string().name("connection_id"),
  direction: __t.string(),
  source: __t.string(),
  destination: __t.string(),
  flags: __t.string(),
  sequence: __t.u32(),
  acknowledgment: __t.u32(),
  window: __t.u32(),
  payloadLength: __t.u32().name("payload_length"),
  capturedAt: __t.timestamp().name("captured_at"),
});
