// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Connection = __t.object("Connection", {
  id: __t.string(),
  source: __t.string(),
  destination: __t.string(),
  sourcePort: __t.u16(),
  destinationPort: __t.u16(),
  addressFamily: __t.u8(),
  state: __t.string(),
  packets: __t.u64(),
  bytes: __t.u64(),
  lastSequence: __t.u32(),
  lastAcknowledgment: __t.u32(),
  lastSeen: __t.timestamp(),
  active: __t.bool(),
});
export type Connection = __Infer<typeof Connection>;

export const Endpoint = __t.object("Endpoint", {
  id: __t.string(),
  address: __t.string(),
  port: __t.u16(),
  addressFamily: __t.u8(),
  firstSeen: __t.timestamp(),
  lastSeen: __t.timestamp(),
  packetsSent: __t.u64(),
  packetsReceived: __t.u64(),
  bytesSent: __t.u64(),
  bytesReceived: __t.u64(),
  active: __t.bool(),
});
export type Endpoint = __Infer<typeof Endpoint>;

export const Packet = __t.object("Packet", {
  id: __t.u64(),
  captureId: __t.string(),
  connectionId: __t.string(),
  direction: __t.string(),
  source: __t.string(),
  destination: __t.string(),
  flags: __t.string(),
  sequence: __t.u32(),
  acknowledgment: __t.u32(),
  window: __t.u32(),
  payloadLength: __t.u32(),
  capturedAt: __t.timestamp(),
});
export type Packet = __Infer<typeof Packet>;

