// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import ClearCaptureReducer from "../clear_capture_reducer";
import IngestPacketReducer from "../ingest_packet_reducer";

export type ClearCaptureParams = __Infer<typeof ClearCaptureReducer>;
export type IngestPacketParams = __Infer<typeof IngestPacketReducer>;

