// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::session_phase_type::SessionPhase;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct AdminSessionDiagnostic {
    pub session_uuid: __sdk::Uuid,
    pub player_uuid: __sdk::Uuid,
    pub gateway_identity: __sdk::Identity,
    pub phase: SessionPhase,
    pub age_micros: u64,
    pub lease_remaining_micros: i64,
}

impl __sdk::InModule for AdminSessionDiagnostic {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `AdminSessionDiagnostic`.
///
/// Provides typed access to columns for query building.
pub struct AdminSessionDiagnosticCols {
    pub session_uuid: __sdk::__query_builder::Col<AdminSessionDiagnostic, __sdk::Uuid>,
    pub player_uuid: __sdk::__query_builder::Col<AdminSessionDiagnostic, __sdk::Uuid>,
    pub gateway_identity: __sdk::__query_builder::Col<AdminSessionDiagnostic, __sdk::Identity>,
    pub phase: __sdk::__query_builder::Col<AdminSessionDiagnostic, SessionPhase>,
    pub age_micros: __sdk::__query_builder::Col<AdminSessionDiagnostic, u64>,
    pub lease_remaining_micros: __sdk::__query_builder::Col<AdminSessionDiagnostic, i64>,
}

impl __sdk::__query_builder::HasCols for AdminSessionDiagnostic {
    type Cols = AdminSessionDiagnosticCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        AdminSessionDiagnosticCols {
            session_uuid: __sdk::__query_builder::Col::new(table_name, "session_uuid"),
            player_uuid: __sdk::__query_builder::Col::new(table_name, "player_uuid"),
            gateway_identity: __sdk::__query_builder::Col::new(table_name, "gateway_identity"),
            phase: __sdk::__query_builder::Col::new(table_name, "phase"),
            age_micros: __sdk::__query_builder::Col::new(table_name, "age_micros"),
            lease_remaining_micros: __sdk::__query_builder::Col::new(
                table_name,
                "lease_remaining_micros",
            ),
        }
    }
}
