// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::admin_lease_diagnostic_type::AdminLeaseDiagnostic;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `admin_lease_diagnostic`.
///
/// Obtain a handle from the [`AdminLeaseDiagnosticTableAccess::admin_lease_diagnostic`] method on [`super::RemoteTables`],
/// like `ctx.db.admin_lease_diagnostic()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.admin_lease_diagnostic().on_insert(...)`.
pub struct AdminLeaseDiagnosticTableHandle<'ctx> {
    imp: __sdk::TableHandle<AdminLeaseDiagnostic>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `admin_lease_diagnostic`.
pub struct AdminLeaseDiagnosticTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for AdminLeaseDiagnosticTableAccessor {
    type Row = AdminLeaseDiagnostic;
    type Handle<'db> = AdminLeaseDiagnosticTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.admin_lease_diagnostic()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `admin_lease_diagnostic`.
///
/// Implemented for [`super::RemoteTables`].
pub trait AdminLeaseDiagnosticTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`AdminLeaseDiagnosticTableHandle`], which mediates access to the table `admin_lease_diagnostic`.
    fn admin_lease_diagnostic(&self) -> AdminLeaseDiagnosticTableHandle<'_>;
}

impl AdminLeaseDiagnosticTableAccess for super::RemoteTables {
    fn admin_lease_diagnostic(&self) -> AdminLeaseDiagnosticTableHandle<'_> {
        AdminLeaseDiagnosticTableHandle {
            imp: self
                .imp
                .get_table::<AdminLeaseDiagnostic>("admin_lease_diagnostic"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct AdminLeaseDiagnosticInsertCallbackId(__sdk::CallbackId);
pub struct AdminLeaseDiagnosticDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for AdminLeaseDiagnosticTableHandle<'ctx> {
    type Row = AdminLeaseDiagnostic;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = AdminLeaseDiagnostic> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for AdminLeaseDiagnosticTableHandle<'ctx> {
    type Row = AdminLeaseDiagnostic;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = AdminLeaseDiagnostic> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = AdminLeaseDiagnosticInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AdminLeaseDiagnosticInsertCallbackId {
        AdminLeaseDiagnosticInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AdminLeaseDiagnosticInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = AdminLeaseDiagnosticDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AdminLeaseDiagnosticDeleteCallbackId {
        AdminLeaseDiagnosticDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AdminLeaseDiagnosticDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for AdminLeaseDiagnosticTableHandle<'ctx> {
    type InsertCallbackId = AdminLeaseDiagnosticInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AdminLeaseDiagnosticInsertCallbackId {
        AdminLeaseDiagnosticInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AdminLeaseDiagnosticInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for AdminLeaseDiagnosticTableHandle<'ctx> {
    type DeleteCallbackId = AdminLeaseDiagnosticDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AdminLeaseDiagnosticDeleteCallbackId {
        AdminLeaseDiagnosticDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AdminLeaseDiagnosticDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct AdminLeaseDiagnosticUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for AdminLeaseDiagnosticTableHandle<'ctx> {
    type UpdateCallbackId = AdminLeaseDiagnosticUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> AdminLeaseDiagnosticUpdateCallbackId {
        AdminLeaseDiagnosticUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: AdminLeaseDiagnosticUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for AdminLeaseDiagnosticTableHandle<'ctx> {
    type UpdateCallbackId = AdminLeaseDiagnosticUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> AdminLeaseDiagnosticUpdateCallbackId {
        AdminLeaseDiagnosticUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: AdminLeaseDiagnosticUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `admin_lease_diagnostic`,
/// which allows point queries on the field of the same name
/// via the [`AdminLeaseDiagnosticIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.admin_lease_diagnostic().id().find(...)`.
pub struct AdminLeaseDiagnosticIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<AdminLeaseDiagnostic, u8>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> AdminLeaseDiagnosticTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `admin_lease_diagnostic`.
    pub fn id(&self) -> AdminLeaseDiagnosticIdUnique<'ctx> {
        AdminLeaseDiagnosticIdUnique {
            imp: self.imp.get_unique_constraint::<u8>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> AdminLeaseDiagnosticIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u8) -> Option<AdminLeaseDiagnostic> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<AdminLeaseDiagnostic>("admin_lease_diagnostic");
    _table.add_unique_constraint::<u8>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<AdminLeaseDiagnostic>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<AdminLeaseDiagnostic>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `AdminLeaseDiagnostic`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait admin_lease_diagnosticQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `AdminLeaseDiagnostic`.
    fn admin_lease_diagnostic(&self) -> __sdk::__query_builder::Table<AdminLeaseDiagnostic>;
}

impl admin_lease_diagnosticQueryTableAccess for __sdk::QueryTableAccessor {
    fn admin_lease_diagnostic(&self) -> __sdk::__query_builder::Table<AdminLeaseDiagnostic> {
        __sdk::__query_builder::Table::new("admin_lease_diagnostic")
    }
}
