// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::admin_session_diagnostic_type::AdminSessionDiagnostic;
use super::session_phase_type::SessionPhase;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `admin_session_diagnostics`.
///
/// Obtain a handle from the [`AdminSessionDiagnosticsTableAccess::admin_session_diagnostics`] method on [`super::RemoteTables`],
/// like `ctx.db.admin_session_diagnostics()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.admin_session_diagnostics().on_insert(...)`.
pub struct AdminSessionDiagnosticsTableHandle<'ctx> {
    imp: __sdk::TableHandle<AdminSessionDiagnostic>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `admin_session_diagnostics`.
pub struct AdminSessionDiagnosticsTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for AdminSessionDiagnosticsTableAccessor {
    type Row = AdminSessionDiagnostic;
    type Handle<'db> = AdminSessionDiagnosticsTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.admin_session_diagnostics()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `admin_session_diagnostics`.
///
/// Implemented for [`super::RemoteTables`].
pub trait AdminSessionDiagnosticsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`AdminSessionDiagnosticsTableHandle`], which mediates access to the table `admin_session_diagnostics`.
    fn admin_session_diagnostics(&self) -> AdminSessionDiagnosticsTableHandle<'_>;
}

impl AdminSessionDiagnosticsTableAccess for super::RemoteTables {
    fn admin_session_diagnostics(&self) -> AdminSessionDiagnosticsTableHandle<'_> {
        AdminSessionDiagnosticsTableHandle {
            imp: self
                .imp
                .get_table::<AdminSessionDiagnostic>("admin_session_diagnostics"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct AdminSessionDiagnosticsInsertCallbackId(__sdk::CallbackId);
pub struct AdminSessionDiagnosticsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for AdminSessionDiagnosticsTableHandle<'ctx> {
    type Row = AdminSessionDiagnostic;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = AdminSessionDiagnostic> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for AdminSessionDiagnosticsTableHandle<'ctx> {
    type Row = AdminSessionDiagnostic;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = AdminSessionDiagnostic> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = AdminSessionDiagnosticsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AdminSessionDiagnosticsInsertCallbackId {
        AdminSessionDiagnosticsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AdminSessionDiagnosticsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = AdminSessionDiagnosticsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AdminSessionDiagnosticsDeleteCallbackId {
        AdminSessionDiagnosticsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AdminSessionDiagnosticsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for AdminSessionDiagnosticsTableHandle<'ctx> {
    type InsertCallbackId = AdminSessionDiagnosticsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AdminSessionDiagnosticsInsertCallbackId {
        AdminSessionDiagnosticsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AdminSessionDiagnosticsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for AdminSessionDiagnosticsTableHandle<'ctx> {
    type DeleteCallbackId = AdminSessionDiagnosticsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AdminSessionDiagnosticsDeleteCallbackId {
        AdminSessionDiagnosticsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AdminSessionDiagnosticsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct AdminSessionDiagnosticsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for AdminSessionDiagnosticsTableHandle<'ctx> {
    type UpdateCallbackId = AdminSessionDiagnosticsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> AdminSessionDiagnosticsUpdateCallbackId {
        AdminSessionDiagnosticsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: AdminSessionDiagnosticsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for AdminSessionDiagnosticsTableHandle<'ctx> {
    type UpdateCallbackId = AdminSessionDiagnosticsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> AdminSessionDiagnosticsUpdateCallbackId {
        AdminSessionDiagnosticsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: AdminSessionDiagnosticsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table =
        client_cache.get_or_make_table::<AdminSessionDiagnostic>("admin_session_diagnostics");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<AdminSessionDiagnostic>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<AdminSessionDiagnostic>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `AdminSessionDiagnostic`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait admin_session_diagnosticsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `AdminSessionDiagnostic`.
    fn admin_session_diagnostics(&self) -> __sdk::__query_builder::Table<AdminSessionDiagnostic>;
}

impl admin_session_diagnosticsQueryTableAccess for __sdk::QueryTableAccessor {
    fn admin_session_diagnostics(&self) -> __sdk::__query_builder::Table<AdminSessionDiagnostic> {
        __sdk::__query_builder::Table::new("admin_session_diagnostics")
    }
}
