// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct AdminLeaseDiagnostic {
    pub id: u8,
    pub session_rows: u64,
    pub expired_awaiting_cleanup: u64,
    pub expired_total: u64,
    pub last_expired_at: Option<__sdk::Timestamp>,
}

impl __sdk::InModule for AdminLeaseDiagnostic {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `AdminLeaseDiagnostic`.
///
/// Provides typed access to columns for query building.
pub struct AdminLeaseDiagnosticCols {
    pub id: __sdk::__query_builder::Col<AdminLeaseDiagnostic, u8>,
    pub session_rows: __sdk::__query_builder::Col<AdminLeaseDiagnostic, u64>,
    pub expired_awaiting_cleanup: __sdk::__query_builder::Col<AdminLeaseDiagnostic, u64>,
    pub expired_total: __sdk::__query_builder::Col<AdminLeaseDiagnostic, u64>,
    pub last_expired_at:
        __sdk::__query_builder::Col<AdminLeaseDiagnostic, Option<__sdk::Timestamp>>,
}

impl __sdk::__query_builder::HasCols for AdminLeaseDiagnostic {
    type Cols = AdminLeaseDiagnosticCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        AdminLeaseDiagnosticCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            session_rows: __sdk::__query_builder::Col::new(table_name, "session_rows"),
            expired_awaiting_cleanup: __sdk::__query_builder::Col::new(
                table_name,
                "expired_awaiting_cleanup",
            ),
            expired_total: __sdk::__query_builder::Col::new(table_name, "expired_total"),
            last_expired_at: __sdk::__query_builder::Col::new(table_name, "last_expired_at"),
        }
    }
}
