// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AdvanceLoginSessionArgs {
    pub session_uuid: __sdk::Uuid,
}

impl From<AdvanceLoginSessionArgs> for super::Reducer {
    fn from(args: AdvanceLoginSessionArgs) -> Self {
        Self::AdvanceLoginSession {
            session_uuid: args.session_uuid,
        }
    }
}

impl __sdk::InModule for AdvanceLoginSessionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `advance_login_session`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait advance_login_session {
    /// Request that the remote module invoke the reducer `advance_login_session` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`advance_login_session:advance_login_session_then`] to run a callback after the reducer completes.
    fn advance_login_session(&self, session_uuid: __sdk::Uuid) -> __sdk::Result<()> {
        self.advance_login_session_then(session_uuid, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `advance_login_session` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn advance_login_session_then(
        &self,
        session_uuid: __sdk::Uuid,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl advance_login_session for super::RemoteReducers {
    fn advance_login_session_then(
        &self,
        session_uuid: __sdk::Uuid,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(AdvanceLoginSessionArgs { session_uuid }, callback)
    }
}
