// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ApplyInventoryRequestArgs {
    pub session_uuid: __sdk::Uuid,
    pub sequence: u64,
    pub payload: Vec<u8>,
}

impl From<ApplyInventoryRequestArgs> for super::Reducer {
    fn from(args: ApplyInventoryRequestArgs) -> Self {
        Self::ApplyInventoryRequest {
            session_uuid: args.session_uuid,
            sequence: args.sequence,
            payload: args.payload,
        }
    }
}

impl __sdk::InModule for ApplyInventoryRequestArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `apply_inventory_request`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait apply_inventory_request {
    /// Request that the remote module invoke the reducer `apply_inventory_request` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`apply_inventory_request:apply_inventory_request_then`] to run a callback after the reducer completes.
    fn apply_inventory_request(
        &self,
        session_uuid: __sdk::Uuid,
        sequence: u64,
        payload: Vec<u8>,
    ) -> __sdk::Result<()> {
        self.apply_inventory_request_then(session_uuid, sequence, payload, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `apply_inventory_request` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn apply_inventory_request_then(
        &self,
        session_uuid: __sdk::Uuid,
        sequence: u64,
        payload: Vec<u8>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl apply_inventory_request for super::RemoteReducers {
    fn apply_inventory_request_then(
        &self,
        session_uuid: __sdk::Uuid,
        sequence: u64,
        payload: Vec<u8>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            ApplyInventoryRequestArgs {
                session_uuid,
                sequence,
                payload,
            },
            callback,
        )
    }
}
