// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ApplyBlockActionArgs {
    pub session_uuid: __sdk::Uuid,
    pub sequence: u64,
    pub x: i32,
    pub y: i32,
    pub z: i32,
    pub expected_state: u32,
    pub place: bool,
}

impl From<ApplyBlockActionArgs> for super::Reducer {
    fn from(args: ApplyBlockActionArgs) -> Self {
        Self::ApplyBlockAction {
            session_uuid: args.session_uuid,
            sequence: args.sequence,
            x: args.x,
            y: args.y,
            z: args.z,
            expected_state: args.expected_state,
            place: args.place,
        }
    }
}

impl __sdk::InModule for ApplyBlockActionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `apply_block_action`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait apply_block_action {
    /// Request that the remote module invoke the reducer `apply_block_action` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`apply_block_action:apply_block_action_then`] to run a callback after the reducer completes.
    fn apply_block_action(
        &self,
        session_uuid: __sdk::Uuid,
        sequence: u64,
        x: i32,
        y: i32,
        z: i32,
        expected_state: u32,
        place: bool,
    ) -> __sdk::Result<()> {
        self.apply_block_action_then(
            session_uuid,
            sequence,
            x,
            y,
            z,
            expected_state,
            place,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `apply_block_action` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn apply_block_action_then(
        &self,
        session_uuid: __sdk::Uuid,
        sequence: u64,
        x: i32,
        y: i32,
        z: i32,
        expected_state: u32,
        place: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl apply_block_action for super::RemoteReducers {
    fn apply_block_action_then(
        &self,
        session_uuid: __sdk::Uuid,
        sequence: u64,
        x: i32,
        y: i32,
        z: i32,
        expected_state: u32,
        place: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            ApplyBlockActionArgs {
                session_uuid,
                sequence,
                x,
                y,
                z,
                expected_state,
                place,
            },
            callback,
        )
    }
}
