// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct BeginOfflineSessionArgs {
    pub session_uuid: __sdk::Uuid,
    pub username: String,
}

impl From<BeginOfflineSessionArgs> for super::Reducer {
    fn from(args: BeginOfflineSessionArgs) -> Self {
        Self::BeginOfflineSession {
            session_uuid: args.session_uuid,
            username: args.username,
        }
    }
}

impl __sdk::InModule for BeginOfflineSessionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `begin_offline_session`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait begin_offline_session {
    /// Request that the remote module invoke the reducer `begin_offline_session` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`begin_offline_session:begin_offline_session_then`] to run a callback after the reducer completes.
    fn begin_offline_session(
        &self,
        session_uuid: __sdk::Uuid,
        username: String,
    ) -> __sdk::Result<()> {
        self.begin_offline_session_then(session_uuid, username, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `begin_offline_session` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn begin_offline_session_then(
        &self,
        session_uuid: __sdk::Uuid,
        username: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl begin_offline_session for super::RemoteReducers {
    fn begin_offline_session_then(
        &self,
        session_uuid: __sdk::Uuid,
        username: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            BeginOfflineSessionArgs {
                session_uuid,
                username,
            },
            callback,
        )
    }
}
