// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct BlockActionRate {
    pub session_uuid: __sdk::Uuid,
    pub window_started_micros: i64,
    pub action_count: u8,
}

impl __sdk::InModule for BlockActionRate {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `BlockActionRate`.
///
/// Provides typed access to columns for query building.
pub struct BlockActionRateCols {
    pub session_uuid: __sdk::__query_builder::Col<BlockActionRate, __sdk::Uuid>,
    pub window_started_micros: __sdk::__query_builder::Col<BlockActionRate, i64>,
    pub action_count: __sdk::__query_builder::Col<BlockActionRate, u8>,
}

impl __sdk::__query_builder::HasCols for BlockActionRate {
    type Cols = BlockActionRateCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        BlockActionRateCols {
            session_uuid: __sdk::__query_builder::Col::new(table_name, "session_uuid"),
            window_started_micros: __sdk::__query_builder::Col::new(
                table_name,
                "window_started_micros",
            ),
            action_count: __sdk::__query_builder::Col::new(table_name, "action_count"),
        }
    }
}

/// Indexed column accessor struct for the table `BlockActionRate`.
///
/// Provides typed access to indexed columns for query building.
pub struct BlockActionRateIxCols {
    pub session_uuid: __sdk::__query_builder::IxCol<BlockActionRate, __sdk::Uuid>,
}

impl __sdk::__query_builder::HasIxCols for BlockActionRate {
    type IxCols = BlockActionRateIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        BlockActionRateIxCols {
            session_uuid: __sdk::__query_builder::IxCol::new(table_name, "session_uuid"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for BlockActionRate {}
