// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct BlockActionState {
    pub session_uuid: __sdk::Uuid,
    pub gateway_identity: __sdk::Identity,
    pub sequence: u64,
    pub x: i32,
    pub y: i32,
    pub z: i32,
    pub expected_state: u32,
    pub resulting_state: u32,
    pub revision: u64,
}

impl __sdk::InModule for BlockActionState {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `BlockActionState`.
///
/// Provides typed access to columns for query building.
pub struct BlockActionStateCols {
    pub session_uuid: __sdk::__query_builder::Col<BlockActionState, __sdk::Uuid>,
    pub gateway_identity: __sdk::__query_builder::Col<BlockActionState, __sdk::Identity>,
    pub sequence: __sdk::__query_builder::Col<BlockActionState, u64>,
    pub x: __sdk::__query_builder::Col<BlockActionState, i32>,
    pub y: __sdk::__query_builder::Col<BlockActionState, i32>,
    pub z: __sdk::__query_builder::Col<BlockActionState, i32>,
    pub expected_state: __sdk::__query_builder::Col<BlockActionState, u32>,
    pub resulting_state: __sdk::__query_builder::Col<BlockActionState, u32>,
    pub revision: __sdk::__query_builder::Col<BlockActionState, u64>,
}

impl __sdk::__query_builder::HasCols for BlockActionState {
    type Cols = BlockActionStateCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        BlockActionStateCols {
            session_uuid: __sdk::__query_builder::Col::new(table_name, "session_uuid"),
            gateway_identity: __sdk::__query_builder::Col::new(table_name, "gateway_identity"),
            sequence: __sdk::__query_builder::Col::new(table_name, "sequence"),
            x: __sdk::__query_builder::Col::new(table_name, "x"),
            y: __sdk::__query_builder::Col::new(table_name, "y"),
            z: __sdk::__query_builder::Col::new(table_name, "z"),
            expected_state: __sdk::__query_builder::Col::new(table_name, "expected_state"),
            resulting_state: __sdk::__query_builder::Col::new(table_name, "resulting_state"),
            revision: __sdk::__query_builder::Col::new(table_name, "revision"),
        }
    }
}

/// Indexed column accessor struct for the table `BlockActionState`.
///
/// Provides typed access to indexed columns for query building.
pub struct BlockActionStateIxCols {
    pub session_uuid: __sdk::__query_builder::IxCol<BlockActionState, __sdk::Uuid>,
}

impl __sdk::__query_builder::HasIxCols for BlockActionState {
    type IxCols = BlockActionStateIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        BlockActionStateIxCols {
            session_uuid: __sdk::__query_builder::IxCol::new(table_name, "session_uuid"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for BlockActionState {}
