// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct BlockOverride {
    pub block_key: String,
    pub chunk_key: String,
    pub world_id: String,
    pub chunk_x: i32,
    pub chunk_z: i32,
    pub x: i32,
    pub y: i32,
    pub z: i32,
    pub state_id: u32,
    pub revision: u64,
    pub updated_by: __sdk::Uuid,
}

impl __sdk::InModule for BlockOverride {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `BlockOverride`.
///
/// Provides typed access to columns for query building.
pub struct BlockOverrideCols {
    pub block_key: __sdk::__query_builder::Col<BlockOverride, String>,
    pub chunk_key: __sdk::__query_builder::Col<BlockOverride, String>,
    pub world_id: __sdk::__query_builder::Col<BlockOverride, String>,
    pub chunk_x: __sdk::__query_builder::Col<BlockOverride, i32>,
    pub chunk_z: __sdk::__query_builder::Col<BlockOverride, i32>,
    pub x: __sdk::__query_builder::Col<BlockOverride, i32>,
    pub y: __sdk::__query_builder::Col<BlockOverride, i32>,
    pub z: __sdk::__query_builder::Col<BlockOverride, i32>,
    pub state_id: __sdk::__query_builder::Col<BlockOverride, u32>,
    pub revision: __sdk::__query_builder::Col<BlockOverride, u64>,
    pub updated_by: __sdk::__query_builder::Col<BlockOverride, __sdk::Uuid>,
}

impl __sdk::__query_builder::HasCols for BlockOverride {
    type Cols = BlockOverrideCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        BlockOverrideCols {
            block_key: __sdk::__query_builder::Col::new(table_name, "block_key"),
            chunk_key: __sdk::__query_builder::Col::new(table_name, "chunk_key"),
            world_id: __sdk::__query_builder::Col::new(table_name, "world_id"),
            chunk_x: __sdk::__query_builder::Col::new(table_name, "chunk_x"),
            chunk_z: __sdk::__query_builder::Col::new(table_name, "chunk_z"),
            x: __sdk::__query_builder::Col::new(table_name, "x"),
            y: __sdk::__query_builder::Col::new(table_name, "y"),
            z: __sdk::__query_builder::Col::new(table_name, "z"),
            state_id: __sdk::__query_builder::Col::new(table_name, "state_id"),
            revision: __sdk::__query_builder::Col::new(table_name, "revision"),
            updated_by: __sdk::__query_builder::Col::new(table_name, "updated_by"),
        }
    }
}

/// Indexed column accessor struct for the table `BlockOverride`.
///
/// Provides typed access to indexed columns for query building.
pub struct BlockOverrideIxCols {
    pub block_key: __sdk::__query_builder::IxCol<BlockOverride, String>,
    pub chunk_key: __sdk::__query_builder::IxCol<BlockOverride, String>,
}

impl __sdk::__query_builder::HasIxCols for BlockOverride {
    type IxCols = BlockOverrideIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        BlockOverrideIxCols {
            block_key: __sdk::__query_builder::IxCol::new(table_name, "block_key"),
            chunk_key: __sdk::__query_builder::IxCol::new(table_name, "chunk_key"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for BlockOverride {}
