// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::game_mode_type::GameMode;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ChangeGameModeArgs {
    pub session_uuid: __sdk::Uuid,
    pub mode: GameMode,
}

impl From<ChangeGameModeArgs> for super::Reducer {
    fn from(args: ChangeGameModeArgs) -> Self {
        Self::ChangeGameMode {
            session_uuid: args.session_uuid,
            mode: args.mode,
        }
    }
}

impl __sdk::InModule for ChangeGameModeArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `change_game_mode`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait change_game_mode {
    /// Request that the remote module invoke the reducer `change_game_mode` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`change_game_mode:change_game_mode_then`] to run a callback after the reducer completes.
    fn change_game_mode(&self, session_uuid: __sdk::Uuid, mode: GameMode) -> __sdk::Result<()> {
        self.change_game_mode_then(session_uuid, mode, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `change_game_mode` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn change_game_mode_then(
        &self,
        session_uuid: __sdk::Uuid,
        mode: GameMode,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl change_game_mode for super::RemoteReducers {
    fn change_game_mode_then(
        &self,
        session_uuid: __sdk::Uuid,
        mode: GameMode,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(ChangeGameModeArgs { session_uuid, mode }, callback)
    }
}
