// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DefineSimpleStorageArgs {
    pub storage_uuid: __sdk::Uuid,
    pub title: String,
}

impl From<DefineSimpleStorageArgs> for super::Reducer {
    fn from(args: DefineSimpleStorageArgs) -> Self {
        Self::DefineSimpleStorage {
            storage_uuid: args.storage_uuid,
            title: args.title,
        }
    }
}

impl __sdk::InModule for DefineSimpleStorageArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `define_simple_storage`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait define_simple_storage {
    /// Request that the remote module invoke the reducer `define_simple_storage` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`define_simple_storage:define_simple_storage_then`] to run a callback after the reducer completes.
    fn define_simple_storage(&self, storage_uuid: __sdk::Uuid, title: String) -> __sdk::Result<()> {
        self.define_simple_storage_then(storage_uuid, title, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `define_simple_storage` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn define_simple_storage_then(
        &self,
        storage_uuid: __sdk::Uuid,
        title: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl define_simple_storage for super::RemoteReducers {
    fn define_simple_storage_then(
        &self,
        storage_uuid: __sdk::Uuid,
        title: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            DefineSimpleStorageArgs {
                storage_uuid,
                title,
            },
            callback,
        )
    }
}
