// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::inventory_snapshot_type::InventorySnapshot;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `gateway_inventory_snapshots`.
///
/// Obtain a handle from the [`GatewayInventorySnapshotsTableAccess::gateway_inventory_snapshots`] method on [`super::RemoteTables`],
/// like `ctx.db.gateway_inventory_snapshots()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.gateway_inventory_snapshots().on_insert(...)`.
pub struct GatewayInventorySnapshotsTableHandle<'ctx> {
    imp: __sdk::TableHandle<InventorySnapshot>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `gateway_inventory_snapshots`.
pub struct GatewayInventorySnapshotsTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for GatewayInventorySnapshotsTableAccessor {
    type Row = InventorySnapshot;
    type Handle<'db> = GatewayInventorySnapshotsTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.gateway_inventory_snapshots()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `gateway_inventory_snapshots`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GatewayInventorySnapshotsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GatewayInventorySnapshotsTableHandle`], which mediates access to the table `gateway_inventory_snapshots`.
    fn gateway_inventory_snapshots(&self) -> GatewayInventorySnapshotsTableHandle<'_>;
}

impl GatewayInventorySnapshotsTableAccess for super::RemoteTables {
    fn gateway_inventory_snapshots(&self) -> GatewayInventorySnapshotsTableHandle<'_> {
        GatewayInventorySnapshotsTableHandle {
            imp: self
                .imp
                .get_table::<InventorySnapshot>("gateway_inventory_snapshots"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GatewayInventorySnapshotsInsertCallbackId(__sdk::CallbackId);
pub struct GatewayInventorySnapshotsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for GatewayInventorySnapshotsTableHandle<'ctx> {
    type Row = InventorySnapshot;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = InventorySnapshot> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for GatewayInventorySnapshotsTableHandle<'ctx> {
    type Row = InventorySnapshot;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = InventorySnapshot> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GatewayInventorySnapshotsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GatewayInventorySnapshotsInsertCallbackId {
        GatewayInventorySnapshotsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GatewayInventorySnapshotsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GatewayInventorySnapshotsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GatewayInventorySnapshotsDeleteCallbackId {
        GatewayInventorySnapshotsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GatewayInventorySnapshotsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for GatewayInventorySnapshotsTableHandle<'ctx> {
    type InsertCallbackId = GatewayInventorySnapshotsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GatewayInventorySnapshotsInsertCallbackId {
        GatewayInventorySnapshotsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GatewayInventorySnapshotsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for GatewayInventorySnapshotsTableHandle<'ctx> {
    type DeleteCallbackId = GatewayInventorySnapshotsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GatewayInventorySnapshotsDeleteCallbackId {
        GatewayInventorySnapshotsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GatewayInventorySnapshotsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct GatewayInventorySnapshotsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GatewayInventorySnapshotsTableHandle<'ctx> {
    type UpdateCallbackId = GatewayInventorySnapshotsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GatewayInventorySnapshotsUpdateCallbackId {
        GatewayInventorySnapshotsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GatewayInventorySnapshotsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for GatewayInventorySnapshotsTableHandle<'ctx> {
    type UpdateCallbackId = GatewayInventorySnapshotsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GatewayInventorySnapshotsUpdateCallbackId {
        GatewayInventorySnapshotsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GatewayInventorySnapshotsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<InventorySnapshot>("gateway_inventory_snapshots");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<InventorySnapshot>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<InventorySnapshot>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `InventorySnapshot`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait gateway_inventory_snapshotsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `InventorySnapshot`.
    fn gateway_inventory_snapshots(&self) -> __sdk::__query_builder::Table<InventorySnapshot>;
}

impl gateway_inventory_snapshotsQueryTableAccess for __sdk::QueryTableAccessor {
    fn gateway_inventory_snapshots(&self) -> __sdk::__query_builder::Table<InventorySnapshot> {
        __sdk::__query_builder::Table::new("gateway_inventory_snapshots")
    }
}
