// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct GatewayWorldPlayer {
    pub session_uuid: __sdk::Uuid,
    pub player_uuid: __sdk::Uuid,
    pub username: String,
    pub entity_id: i32,
    pub x: f64,
    pub y: f64,
    pub z: f64,
    pub yaw: f32,
    pub pitch: f32,
    pub on_ground: bool,
    pub revision: u64,
}

impl __sdk::InModule for GatewayWorldPlayer {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `GatewayWorldPlayer`.
///
/// Provides typed access to columns for query building.
pub struct GatewayWorldPlayerCols {
    pub session_uuid: __sdk::__query_builder::Col<GatewayWorldPlayer, __sdk::Uuid>,
    pub player_uuid: __sdk::__query_builder::Col<GatewayWorldPlayer, __sdk::Uuid>,
    pub username: __sdk::__query_builder::Col<GatewayWorldPlayer, String>,
    pub entity_id: __sdk::__query_builder::Col<GatewayWorldPlayer, i32>,
    pub x: __sdk::__query_builder::Col<GatewayWorldPlayer, f64>,
    pub y: __sdk::__query_builder::Col<GatewayWorldPlayer, f64>,
    pub z: __sdk::__query_builder::Col<GatewayWorldPlayer, f64>,
    pub yaw: __sdk::__query_builder::Col<GatewayWorldPlayer, f32>,
    pub pitch: __sdk::__query_builder::Col<GatewayWorldPlayer, f32>,
    pub on_ground: __sdk::__query_builder::Col<GatewayWorldPlayer, bool>,
    pub revision: __sdk::__query_builder::Col<GatewayWorldPlayer, u64>,
}

impl __sdk::__query_builder::HasCols for GatewayWorldPlayer {
    type Cols = GatewayWorldPlayerCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        GatewayWorldPlayerCols {
            session_uuid: __sdk::__query_builder::Col::new(table_name, "session_uuid"),
            player_uuid: __sdk::__query_builder::Col::new(table_name, "player_uuid"),
            username: __sdk::__query_builder::Col::new(table_name, "username"),
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            x: __sdk::__query_builder::Col::new(table_name, "x"),
            y: __sdk::__query_builder::Col::new(table_name, "y"),
            z: __sdk::__query_builder::Col::new(table_name, "z"),
            yaw: __sdk::__query_builder::Col::new(table_name, "yaw"),
            pitch: __sdk::__query_builder::Col::new(table_name, "pitch"),
            on_ground: __sdk::__query_builder::Col::new(table_name, "on_ground"),
            revision: __sdk::__query_builder::Col::new(table_name, "revision"),
        }
    }
}
