// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Gateway {
    pub identity: __sdk::Identity,
}

impl __sdk::InModule for Gateway {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Gateway`.
///
/// Provides typed access to columns for query building.
pub struct GatewayCols {
    pub identity: __sdk::__query_builder::Col<Gateway, __sdk::Identity>,
}

impl __sdk::__query_builder::HasCols for Gateway {
    type Cols = GatewayCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        GatewayCols {
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
        }
    }
}

/// Indexed column accessor struct for the table `Gateway`.
///
/// Provides typed access to indexed columns for query building.
pub struct GatewayIxCols {
    pub identity: __sdk::__query_builder::IxCol<Gateway, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for Gateway {
    type IxCols = GatewayIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        GatewayIxCols {
            identity: __sdk::__query_builder::IxCol::new(table_name, "identity"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Gateway {}
