// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::gateway_world_player_type::GatewayWorldPlayer;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `gateway_world_players`.
///
/// Obtain a handle from the [`GatewayWorldPlayersTableAccess::gateway_world_players`] method on [`super::RemoteTables`],
/// like `ctx.db.gateway_world_players()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.gateway_world_players().on_insert(...)`.
pub struct GatewayWorldPlayersTableHandle<'ctx> {
    imp: __sdk::TableHandle<GatewayWorldPlayer>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `gateway_world_players`.
pub struct GatewayWorldPlayersTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for GatewayWorldPlayersTableAccessor {
    type Row = GatewayWorldPlayer;
    type Handle<'db> = GatewayWorldPlayersTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.gateway_world_players()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `gateway_world_players`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GatewayWorldPlayersTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GatewayWorldPlayersTableHandle`], which mediates access to the table `gateway_world_players`.
    fn gateway_world_players(&self) -> GatewayWorldPlayersTableHandle<'_>;
}

impl GatewayWorldPlayersTableAccess for super::RemoteTables {
    fn gateway_world_players(&self) -> GatewayWorldPlayersTableHandle<'_> {
        GatewayWorldPlayersTableHandle {
            imp: self
                .imp
                .get_table::<GatewayWorldPlayer>("gateway_world_players"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GatewayWorldPlayersInsertCallbackId(__sdk::CallbackId);
pub struct GatewayWorldPlayersDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for GatewayWorldPlayersTableHandle<'ctx> {
    type Row = GatewayWorldPlayer;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = GatewayWorldPlayer> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for GatewayWorldPlayersTableHandle<'ctx> {
    type Row = GatewayWorldPlayer;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = GatewayWorldPlayer> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GatewayWorldPlayersInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GatewayWorldPlayersInsertCallbackId {
        GatewayWorldPlayersInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GatewayWorldPlayersInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GatewayWorldPlayersDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GatewayWorldPlayersDeleteCallbackId {
        GatewayWorldPlayersDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GatewayWorldPlayersDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for GatewayWorldPlayersTableHandle<'ctx> {
    type InsertCallbackId = GatewayWorldPlayersInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GatewayWorldPlayersInsertCallbackId {
        GatewayWorldPlayersInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GatewayWorldPlayersInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for GatewayWorldPlayersTableHandle<'ctx> {
    type DeleteCallbackId = GatewayWorldPlayersDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GatewayWorldPlayersDeleteCallbackId {
        GatewayWorldPlayersDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GatewayWorldPlayersDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct GatewayWorldPlayersUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GatewayWorldPlayersTableHandle<'ctx> {
    type UpdateCallbackId = GatewayWorldPlayersUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GatewayWorldPlayersUpdateCallbackId {
        GatewayWorldPlayersUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GatewayWorldPlayersUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for GatewayWorldPlayersTableHandle<'ctx> {
    type UpdateCallbackId = GatewayWorldPlayersUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GatewayWorldPlayersUpdateCallbackId {
        GatewayWorldPlayersUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GatewayWorldPlayersUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<GatewayWorldPlayer>("gateway_world_players");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<GatewayWorldPlayer>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<GatewayWorldPlayer>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `GatewayWorldPlayer`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait gateway_world_playersQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `GatewayWorldPlayer`.
    fn gateway_world_players(&self) -> __sdk::__query_builder::Table<GatewayWorldPlayer>;
}

impl gateway_world_playersQueryTableAccess for __sdk::QueryTableAccessor {
    fn gateway_world_players(&self) -> __sdk::__query_builder::Table<GatewayWorldPlayer> {
        __sdk::__query_builder::Table::new("gateway_world_players")
    }
}
