// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::gateway_block_action_type::GatewayBlockAction;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `gateway_block_actions`.
///
/// Obtain a handle from the [`GatewayBlockActionsTableAccess::gateway_block_actions`] method on [`super::RemoteTables`],
/// like `ctx.db.gateway_block_actions()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.gateway_block_actions().on_insert(...)`.
pub struct GatewayBlockActionsTableHandle<'ctx> {
    imp: __sdk::TableHandle<GatewayBlockAction>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `gateway_block_actions`.
pub struct GatewayBlockActionsTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for GatewayBlockActionsTableAccessor {
    type Row = GatewayBlockAction;
    type Handle<'db> = GatewayBlockActionsTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.gateway_block_actions()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `gateway_block_actions`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GatewayBlockActionsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GatewayBlockActionsTableHandle`], which mediates access to the table `gateway_block_actions`.
    fn gateway_block_actions(&self) -> GatewayBlockActionsTableHandle<'_>;
}

impl GatewayBlockActionsTableAccess for super::RemoteTables {
    fn gateway_block_actions(&self) -> GatewayBlockActionsTableHandle<'_> {
        GatewayBlockActionsTableHandle {
            imp: self
                .imp
                .get_table::<GatewayBlockAction>("gateway_block_actions"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GatewayBlockActionsInsertCallbackId(__sdk::CallbackId);
pub struct GatewayBlockActionsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for GatewayBlockActionsTableHandle<'ctx> {
    type Row = GatewayBlockAction;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = GatewayBlockAction> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for GatewayBlockActionsTableHandle<'ctx> {
    type Row = GatewayBlockAction;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = GatewayBlockAction> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GatewayBlockActionsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GatewayBlockActionsInsertCallbackId {
        GatewayBlockActionsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GatewayBlockActionsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GatewayBlockActionsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GatewayBlockActionsDeleteCallbackId {
        GatewayBlockActionsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GatewayBlockActionsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for GatewayBlockActionsTableHandle<'ctx> {
    type InsertCallbackId = GatewayBlockActionsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GatewayBlockActionsInsertCallbackId {
        GatewayBlockActionsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GatewayBlockActionsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for GatewayBlockActionsTableHandle<'ctx> {
    type DeleteCallbackId = GatewayBlockActionsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GatewayBlockActionsDeleteCallbackId {
        GatewayBlockActionsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GatewayBlockActionsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct GatewayBlockActionsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GatewayBlockActionsTableHandle<'ctx> {
    type UpdateCallbackId = GatewayBlockActionsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GatewayBlockActionsUpdateCallbackId {
        GatewayBlockActionsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GatewayBlockActionsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for GatewayBlockActionsTableHandle<'ctx> {
    type UpdateCallbackId = GatewayBlockActionsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GatewayBlockActionsUpdateCallbackId {
        GatewayBlockActionsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GatewayBlockActionsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<GatewayBlockAction>("gateway_block_actions");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<GatewayBlockAction>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<GatewayBlockAction>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `GatewayBlockAction`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait gateway_block_actionsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `GatewayBlockAction`.
    fn gateway_block_actions(&self) -> __sdk::__query_builder::Table<GatewayBlockAction>;
}

impl gateway_block_actionsQueryTableAccess for __sdk::QueryTableAccessor {
    fn gateway_block_actions(&self) -> __sdk::__query_builder::Table<GatewayBlockAction> {
        __sdk::__query_builder::Table::new("gateway_block_actions")
    }
}
