// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::game_mode_type::GameMode;
use super::gateway_player_state_type::GatewayPlayerState;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `gateway_player_state`.
///
/// Obtain a handle from the [`GatewayPlayerStateTableAccess::gateway_player_state`] method on [`super::RemoteTables`],
/// like `ctx.db.gateway_player_state()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.gateway_player_state().on_insert(...)`.
pub struct GatewayPlayerStateTableHandle<'ctx> {
    imp: __sdk::TableHandle<GatewayPlayerState>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `gateway_player_state`.
pub struct GatewayPlayerStateTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for GatewayPlayerStateTableAccessor {
    type Row = GatewayPlayerState;
    type Handle<'db> = GatewayPlayerStateTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.gateway_player_state()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `gateway_player_state`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GatewayPlayerStateTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GatewayPlayerStateTableHandle`], which mediates access to the table `gateway_player_state`.
    fn gateway_player_state(&self) -> GatewayPlayerStateTableHandle<'_>;
}

impl GatewayPlayerStateTableAccess for super::RemoteTables {
    fn gateway_player_state(&self) -> GatewayPlayerStateTableHandle<'_> {
        GatewayPlayerStateTableHandle {
            imp: self
                .imp
                .get_table::<GatewayPlayerState>("gateway_player_state"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GatewayPlayerStateInsertCallbackId(__sdk::CallbackId);
pub struct GatewayPlayerStateDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for GatewayPlayerStateTableHandle<'ctx> {
    type Row = GatewayPlayerState;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = GatewayPlayerState> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for GatewayPlayerStateTableHandle<'ctx> {
    type Row = GatewayPlayerState;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = GatewayPlayerState> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GatewayPlayerStateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GatewayPlayerStateInsertCallbackId {
        GatewayPlayerStateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GatewayPlayerStateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GatewayPlayerStateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GatewayPlayerStateDeleteCallbackId {
        GatewayPlayerStateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GatewayPlayerStateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for GatewayPlayerStateTableHandle<'ctx> {
    type InsertCallbackId = GatewayPlayerStateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GatewayPlayerStateInsertCallbackId {
        GatewayPlayerStateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GatewayPlayerStateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for GatewayPlayerStateTableHandle<'ctx> {
    type DeleteCallbackId = GatewayPlayerStateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GatewayPlayerStateDeleteCallbackId {
        GatewayPlayerStateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GatewayPlayerStateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct GatewayPlayerStateUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GatewayPlayerStateTableHandle<'ctx> {
    type UpdateCallbackId = GatewayPlayerStateUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GatewayPlayerStateUpdateCallbackId {
        GatewayPlayerStateUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GatewayPlayerStateUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for GatewayPlayerStateTableHandle<'ctx> {
    type UpdateCallbackId = GatewayPlayerStateUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GatewayPlayerStateUpdateCallbackId {
        GatewayPlayerStateUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GatewayPlayerStateUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<GatewayPlayerState>("gateway_player_state");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<GatewayPlayerState>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<GatewayPlayerState>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `GatewayPlayerState`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait gateway_player_stateQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `GatewayPlayerState`.
    fn gateway_player_state(&self) -> __sdk::__query_builder::Table<GatewayPlayerState>;
}

impl gateway_player_stateQueryTableAccess for __sdk::QueryTableAccessor {
    fn gateway_player_state(&self) -> __sdk::__query_builder::Table<GatewayPlayerState> {
        __sdk::__query_builder::Table::new("gateway_player_state")
    }
}
