// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct GatewayBlockAction {
    pub session_uuid: __sdk::Uuid,
    pub sequence: u64,
    pub x: i32,
    pub y: i32,
    pub z: i32,
    pub expected_state: u32,
    pub resulting_state: u32,
    pub revision: u64,
}

impl __sdk::InModule for GatewayBlockAction {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `GatewayBlockAction`.
///
/// Provides typed access to columns for query building.
pub struct GatewayBlockActionCols {
    pub session_uuid: __sdk::__query_builder::Col<GatewayBlockAction, __sdk::Uuid>,
    pub sequence: __sdk::__query_builder::Col<GatewayBlockAction, u64>,
    pub x: __sdk::__query_builder::Col<GatewayBlockAction, i32>,
    pub y: __sdk::__query_builder::Col<GatewayBlockAction, i32>,
    pub z: __sdk::__query_builder::Col<GatewayBlockAction, i32>,
    pub expected_state: __sdk::__query_builder::Col<GatewayBlockAction, u32>,
    pub resulting_state: __sdk::__query_builder::Col<GatewayBlockAction, u32>,
    pub revision: __sdk::__query_builder::Col<GatewayBlockAction, u64>,
}

impl __sdk::__query_builder::HasCols for GatewayBlockAction {
    type Cols = GatewayBlockActionCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        GatewayBlockActionCols {
            session_uuid: __sdk::__query_builder::Col::new(table_name, "session_uuid"),
            sequence: __sdk::__query_builder::Col::new(table_name, "sequence"),
            x: __sdk::__query_builder::Col::new(table_name, "x"),
            y: __sdk::__query_builder::Col::new(table_name, "y"),
            z: __sdk::__query_builder::Col::new(table_name, "z"),
            expected_state: __sdk::__query_builder::Col::new(table_name, "expected_state"),
            resulting_state: __sdk::__query_builder::Col::new(table_name, "resulting_state"),
            revision: __sdk::__query_builder::Col::new(table_name, "revision"),
        }
    }
}
