// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::game_mode_type::GameMode;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct GatewayGameMode {
    pub session_uuid: __sdk::Uuid,
    pub mode: GameMode,
}

impl __sdk::InModule for GatewayGameMode {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `GatewayGameMode`.
///
/// Provides typed access to columns for query building.
pub struct GatewayGameModeCols {
    pub session_uuid: __sdk::__query_builder::Col<GatewayGameMode, __sdk::Uuid>,
    pub mode: __sdk::__query_builder::Col<GatewayGameMode, GameMode>,
}

impl __sdk::__query_builder::HasCols for GatewayGameMode {
    type Cols = GatewayGameModeCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        GatewayGameModeCols {
            session_uuid: __sdk::__query_builder::Col::new(table_name, "session_uuid"),
            mode: __sdk::__query_builder::Col::new(table_name, "mode"),
        }
    }
}
