// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::gateway_chat_message_type::GatewayChatMessage;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `gateway_chat_messages`.
///
/// Obtain a handle from the [`GatewayChatMessagesTableAccess::gateway_chat_messages`] method on [`super::RemoteTables`],
/// like `ctx.db.gateway_chat_messages()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.gateway_chat_messages().on_insert(...)`.
pub struct GatewayChatMessagesTableHandle<'ctx> {
    imp: __sdk::TableHandle<GatewayChatMessage>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `gateway_chat_messages`.
pub struct GatewayChatMessagesTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for GatewayChatMessagesTableAccessor {
    type Row = GatewayChatMessage;
    type Handle<'db> = GatewayChatMessagesTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.gateway_chat_messages()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `gateway_chat_messages`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GatewayChatMessagesTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GatewayChatMessagesTableHandle`], which mediates access to the table `gateway_chat_messages`.
    fn gateway_chat_messages(&self) -> GatewayChatMessagesTableHandle<'_>;
}

impl GatewayChatMessagesTableAccess for super::RemoteTables {
    fn gateway_chat_messages(&self) -> GatewayChatMessagesTableHandle<'_> {
        GatewayChatMessagesTableHandle {
            imp: self
                .imp
                .get_table::<GatewayChatMessage>("gateway_chat_messages"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GatewayChatMessagesInsertCallbackId(__sdk::CallbackId);
pub struct GatewayChatMessagesDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for GatewayChatMessagesTableHandle<'ctx> {
    type Row = GatewayChatMessage;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = GatewayChatMessage> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for GatewayChatMessagesTableHandle<'ctx> {
    type Row = GatewayChatMessage;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = GatewayChatMessage> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GatewayChatMessagesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GatewayChatMessagesInsertCallbackId {
        GatewayChatMessagesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GatewayChatMessagesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GatewayChatMessagesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GatewayChatMessagesDeleteCallbackId {
        GatewayChatMessagesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GatewayChatMessagesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for GatewayChatMessagesTableHandle<'ctx> {
    type InsertCallbackId = GatewayChatMessagesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GatewayChatMessagesInsertCallbackId {
        GatewayChatMessagesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GatewayChatMessagesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for GatewayChatMessagesTableHandle<'ctx> {
    type DeleteCallbackId = GatewayChatMessagesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GatewayChatMessagesDeleteCallbackId {
        GatewayChatMessagesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GatewayChatMessagesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct GatewayChatMessagesUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GatewayChatMessagesTableHandle<'ctx> {
    type UpdateCallbackId = GatewayChatMessagesUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GatewayChatMessagesUpdateCallbackId {
        GatewayChatMessagesUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GatewayChatMessagesUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for GatewayChatMessagesTableHandle<'ctx> {
    type UpdateCallbackId = GatewayChatMessagesUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GatewayChatMessagesUpdateCallbackId {
        GatewayChatMessagesUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GatewayChatMessagesUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `message_id` unique index on the table `gateway_chat_messages`,
/// which allows point queries on the field of the same name
/// via the [`GatewayChatMessagesMessageIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.gateway_chat_messages().message_id().find(...)`.
pub struct GatewayChatMessagesMessageIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<GatewayChatMessage, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> GatewayChatMessagesTableHandle<'ctx> {
    /// Get a handle on the `message_id` unique index on the table `gateway_chat_messages`.
    pub fn message_id(&self) -> GatewayChatMessagesMessageIdUnique<'ctx> {
        GatewayChatMessagesMessageIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("message_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> GatewayChatMessagesMessageIdUnique<'ctx> {
    /// Find the subscribed row whose `message_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<GatewayChatMessage> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<GatewayChatMessage>("gateway_chat_messages");
    _table.add_unique_constraint::<u64>("message_id", |row| &row.message_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<GatewayChatMessage>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<GatewayChatMessage>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `GatewayChatMessage`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait gateway_chat_messagesQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `GatewayChatMessage`.
    fn gateway_chat_messages(&self) -> __sdk::__query_builder::Table<GatewayChatMessage>;
}

impl gateway_chat_messagesQueryTableAccess for __sdk::QueryTableAccessor {
    fn gateway_chat_messages(&self) -> __sdk::__query_builder::Table<GatewayChatMessage> {
        __sdk::__query_builder::Table::new("gateway_chat_messages")
    }
}
