// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::identity_kind_type::IdentityKind;
use super::player_profile_type::PlayerProfile;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `gateway_profiles`.
///
/// Obtain a handle from the [`GatewayProfilesTableAccess::gateway_profiles`] method on [`super::RemoteTables`],
/// like `ctx.db.gateway_profiles()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.gateway_profiles().on_insert(...)`.
pub struct GatewayProfilesTableHandle<'ctx> {
    imp: __sdk::TableHandle<PlayerProfile>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `gateway_profiles`.
pub struct GatewayProfilesTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for GatewayProfilesTableAccessor {
    type Row = PlayerProfile;
    type Handle<'db> = GatewayProfilesTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.gateway_profiles()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `gateway_profiles`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GatewayProfilesTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GatewayProfilesTableHandle`], which mediates access to the table `gateway_profiles`.
    fn gateway_profiles(&self) -> GatewayProfilesTableHandle<'_>;
}

impl GatewayProfilesTableAccess for super::RemoteTables {
    fn gateway_profiles(&self) -> GatewayProfilesTableHandle<'_> {
        GatewayProfilesTableHandle {
            imp: self.imp.get_table::<PlayerProfile>("gateway_profiles"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GatewayProfilesInsertCallbackId(__sdk::CallbackId);
pub struct GatewayProfilesDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for GatewayProfilesTableHandle<'ctx> {
    type Row = PlayerProfile;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PlayerProfile> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for GatewayProfilesTableHandle<'ctx> {
    type Row = PlayerProfile;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PlayerProfile> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GatewayProfilesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GatewayProfilesInsertCallbackId {
        GatewayProfilesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GatewayProfilesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GatewayProfilesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GatewayProfilesDeleteCallbackId {
        GatewayProfilesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GatewayProfilesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for GatewayProfilesTableHandle<'ctx> {
    type InsertCallbackId = GatewayProfilesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GatewayProfilesInsertCallbackId {
        GatewayProfilesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GatewayProfilesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for GatewayProfilesTableHandle<'ctx> {
    type DeleteCallbackId = GatewayProfilesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GatewayProfilesDeleteCallbackId {
        GatewayProfilesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GatewayProfilesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct GatewayProfilesUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GatewayProfilesTableHandle<'ctx> {
    type UpdateCallbackId = GatewayProfilesUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GatewayProfilesUpdateCallbackId {
        GatewayProfilesUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GatewayProfilesUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for GatewayProfilesTableHandle<'ctx> {
    type UpdateCallbackId = GatewayProfilesUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GatewayProfilesUpdateCallbackId {
        GatewayProfilesUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GatewayProfilesUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PlayerProfile>("gateway_profiles");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<PlayerProfile>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PlayerProfile>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `PlayerProfile`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait gateway_profilesQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `PlayerProfile`.
    fn gateway_profiles(&self) -> __sdk::__query_builder::Table<PlayerProfile>;
}

impl gateway_profilesQueryTableAccess for __sdk::QueryTableAccessor {
    fn gateway_profiles(&self) -> __sdk::__query_builder::Table<PlayerProfile> {
        __sdk::__query_builder::Table::new("gateway_profiles")
    }
}
