// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::game_mode_type::GameMode;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct GatewayPlayerState {
    pub session_uuid: __sdk::Uuid,
    pub mode: GameMode,
    pub health: u8,
    pub food: u8,
    pub dead: bool,
    pub revision: u64,
    pub respawn_revision: Option<u64>,
    pub state_owner: Option<__sdk::Identity>,
}

impl __sdk::InModule for GatewayPlayerState {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `GatewayPlayerState`.
///
/// Provides typed access to columns for query building.
pub struct GatewayPlayerStateCols {
    pub session_uuid: __sdk::__query_builder::Col<GatewayPlayerState, __sdk::Uuid>,
    pub mode: __sdk::__query_builder::Col<GatewayPlayerState, GameMode>,
    pub health: __sdk::__query_builder::Col<GatewayPlayerState, u8>,
    pub food: __sdk::__query_builder::Col<GatewayPlayerState, u8>,
    pub dead: __sdk::__query_builder::Col<GatewayPlayerState, bool>,
    pub revision: __sdk::__query_builder::Col<GatewayPlayerState, u64>,
    pub respawn_revision: __sdk::__query_builder::Col<GatewayPlayerState, Option<u64>>,
    pub state_owner: __sdk::__query_builder::Col<GatewayPlayerState, Option<__sdk::Identity>>,
}

impl __sdk::__query_builder::HasCols for GatewayPlayerState {
    type Cols = GatewayPlayerStateCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        GatewayPlayerStateCols {
            session_uuid: __sdk::__query_builder::Col::new(table_name, "session_uuid"),
            mode: __sdk::__query_builder::Col::new(table_name, "mode"),
            health: __sdk::__query_builder::Col::new(table_name, "health"),
            food: __sdk::__query_builder::Col::new(table_name, "food"),
            dead: __sdk::__query_builder::Col::new(table_name, "dead"),
            revision: __sdk::__query_builder::Col::new(table_name, "revision"),
            respawn_revision: __sdk::__query_builder::Col::new(table_name, "respawn_revision"),
            state_owner: __sdk::__query_builder::Col::new(table_name, "state_owner"),
        }
    }
}
