// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::player_session_type::PlayerSession;
use super::session_phase_type::SessionPhase;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `gateway_sessions`.
///
/// Obtain a handle from the [`GatewaySessionsTableAccess::gateway_sessions`] method on [`super::RemoteTables`],
/// like `ctx.db.gateway_sessions()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.gateway_sessions().on_insert(...)`.
pub struct GatewaySessionsTableHandle<'ctx> {
    imp: __sdk::TableHandle<PlayerSession>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `gateway_sessions`.
pub struct GatewaySessionsTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for GatewaySessionsTableAccessor {
    type Row = PlayerSession;
    type Handle<'db> = GatewaySessionsTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.gateway_sessions()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `gateway_sessions`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GatewaySessionsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GatewaySessionsTableHandle`], which mediates access to the table `gateway_sessions`.
    fn gateway_sessions(&self) -> GatewaySessionsTableHandle<'_>;
}

impl GatewaySessionsTableAccess for super::RemoteTables {
    fn gateway_sessions(&self) -> GatewaySessionsTableHandle<'_> {
        GatewaySessionsTableHandle {
            imp: self.imp.get_table::<PlayerSession>("gateway_sessions"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GatewaySessionsInsertCallbackId(__sdk::CallbackId);
pub struct GatewaySessionsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for GatewaySessionsTableHandle<'ctx> {
    type Row = PlayerSession;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PlayerSession> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for GatewaySessionsTableHandle<'ctx> {
    type Row = PlayerSession;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PlayerSession> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GatewaySessionsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GatewaySessionsInsertCallbackId {
        GatewaySessionsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GatewaySessionsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GatewaySessionsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GatewaySessionsDeleteCallbackId {
        GatewaySessionsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GatewaySessionsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for GatewaySessionsTableHandle<'ctx> {
    type InsertCallbackId = GatewaySessionsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GatewaySessionsInsertCallbackId {
        GatewaySessionsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GatewaySessionsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for GatewaySessionsTableHandle<'ctx> {
    type DeleteCallbackId = GatewaySessionsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GatewaySessionsDeleteCallbackId {
        GatewaySessionsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GatewaySessionsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct GatewaySessionsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GatewaySessionsTableHandle<'ctx> {
    type UpdateCallbackId = GatewaySessionsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GatewaySessionsUpdateCallbackId {
        GatewaySessionsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GatewaySessionsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for GatewaySessionsTableHandle<'ctx> {
    type UpdateCallbackId = GatewaySessionsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GatewaySessionsUpdateCallbackId {
        GatewaySessionsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GatewaySessionsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PlayerSession>("gateway_sessions");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<PlayerSession>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PlayerSession>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `PlayerSession`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait gateway_sessionsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `PlayerSession`.
    fn gateway_sessions(&self) -> __sdk::__query_builder::Table<PlayerSession>;
}

impl gateway_sessionsQueryTableAccess for __sdk::QueryTableAccessor {
    fn gateway_sessions(&self) -> __sdk::__query_builder::Table<PlayerSession> {
        __sdk::__query_builder::Table::new("gateway_sessions")
    }
}
