// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct GatewayChunkSnapshot {
    pub snapshot_key: String,
    pub world_id: String,
    pub chunk_x: i32,
    pub chunk_z: i32,
    pub encoded_overrides: Vec<u8>,
    pub revision: u64,
}

impl __sdk::InModule for GatewayChunkSnapshot {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `GatewayChunkSnapshot`.
///
/// Provides typed access to columns for query building.
pub struct GatewayChunkSnapshotCols {
    pub snapshot_key: __sdk::__query_builder::Col<GatewayChunkSnapshot, String>,
    pub world_id: __sdk::__query_builder::Col<GatewayChunkSnapshot, String>,
    pub chunk_x: __sdk::__query_builder::Col<GatewayChunkSnapshot, i32>,
    pub chunk_z: __sdk::__query_builder::Col<GatewayChunkSnapshot, i32>,
    pub encoded_overrides: __sdk::__query_builder::Col<GatewayChunkSnapshot, Vec<u8>>,
    pub revision: __sdk::__query_builder::Col<GatewayChunkSnapshot, u64>,
}

impl __sdk::__query_builder::HasCols for GatewayChunkSnapshot {
    type Cols = GatewayChunkSnapshotCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        GatewayChunkSnapshotCols {
            snapshot_key: __sdk::__query_builder::Col::new(table_name, "snapshot_key"),
            world_id: __sdk::__query_builder::Col::new(table_name, "world_id"),
            chunk_x: __sdk::__query_builder::Col::new(table_name, "chunk_x"),
            chunk_z: __sdk::__query_builder::Col::new(table_name, "chunk_z"),
            encoded_overrides: __sdk::__query_builder::Col::new(table_name, "encoded_overrides"),
            revision: __sdk::__query_builder::Col::new(table_name, "revision"),
        }
    }
}
