// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct GatewayChunkState {
    pub snapshot_key: String,
    pub gateway_identity: __sdk::Identity,
    pub world_id: String,
    pub chunk_key: String,
    pub chunk_x: i32,
    pub chunk_z: i32,
    pub encoded_overrides: Vec<u8>,
    pub revision: u64,
}

impl __sdk::InModule for GatewayChunkState {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `GatewayChunkState`.
///
/// Provides typed access to columns for query building.
pub struct GatewayChunkStateCols {
    pub snapshot_key: __sdk::__query_builder::Col<GatewayChunkState, String>,
    pub gateway_identity: __sdk::__query_builder::Col<GatewayChunkState, __sdk::Identity>,
    pub world_id: __sdk::__query_builder::Col<GatewayChunkState, String>,
    pub chunk_key: __sdk::__query_builder::Col<GatewayChunkState, String>,
    pub chunk_x: __sdk::__query_builder::Col<GatewayChunkState, i32>,
    pub chunk_z: __sdk::__query_builder::Col<GatewayChunkState, i32>,
    pub encoded_overrides: __sdk::__query_builder::Col<GatewayChunkState, Vec<u8>>,
    pub revision: __sdk::__query_builder::Col<GatewayChunkState, u64>,
}

impl __sdk::__query_builder::HasCols for GatewayChunkState {
    type Cols = GatewayChunkStateCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        GatewayChunkStateCols {
            snapshot_key: __sdk::__query_builder::Col::new(table_name, "snapshot_key"),
            gateway_identity: __sdk::__query_builder::Col::new(table_name, "gateway_identity"),
            world_id: __sdk::__query_builder::Col::new(table_name, "world_id"),
            chunk_key: __sdk::__query_builder::Col::new(table_name, "chunk_key"),
            chunk_x: __sdk::__query_builder::Col::new(table_name, "chunk_x"),
            chunk_z: __sdk::__query_builder::Col::new(table_name, "chunk_z"),
            encoded_overrides: __sdk::__query_builder::Col::new(table_name, "encoded_overrides"),
            revision: __sdk::__query_builder::Col::new(table_name, "revision"),
        }
    }
}

/// Indexed column accessor struct for the table `GatewayChunkState`.
///
/// Provides typed access to indexed columns for query building.
pub struct GatewayChunkStateIxCols {
    pub snapshot_key: __sdk::__query_builder::IxCol<GatewayChunkState, String>,
}

impl __sdk::__query_builder::HasIxCols for GatewayChunkState {
    type IxCols = GatewayChunkStateIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        GatewayChunkStateIxCols {
            snapshot_key: __sdk::__query_builder::IxCol::new(table_name, "snapshot_key"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for GatewayChunkState {}
