// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::game_mode_type::GameMode;
use super::gateway_game_mode_type::GatewayGameMode;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `gateway_game_modes`.
///
/// Obtain a handle from the [`GatewayGameModesTableAccess::gateway_game_modes`] method on [`super::RemoteTables`],
/// like `ctx.db.gateway_game_modes()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.gateway_game_modes().on_insert(...)`.
pub struct GatewayGameModesTableHandle<'ctx> {
    imp: __sdk::TableHandle<GatewayGameMode>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `gateway_game_modes`.
pub struct GatewayGameModesTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for GatewayGameModesTableAccessor {
    type Row = GatewayGameMode;
    type Handle<'db> = GatewayGameModesTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.gateway_game_modes()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `gateway_game_modes`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GatewayGameModesTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GatewayGameModesTableHandle`], which mediates access to the table `gateway_game_modes`.
    fn gateway_game_modes(&self) -> GatewayGameModesTableHandle<'_>;
}

impl GatewayGameModesTableAccess for super::RemoteTables {
    fn gateway_game_modes(&self) -> GatewayGameModesTableHandle<'_> {
        GatewayGameModesTableHandle {
            imp: self.imp.get_table::<GatewayGameMode>("gateway_game_modes"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GatewayGameModesInsertCallbackId(__sdk::CallbackId);
pub struct GatewayGameModesDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for GatewayGameModesTableHandle<'ctx> {
    type Row = GatewayGameMode;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = GatewayGameMode> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for GatewayGameModesTableHandle<'ctx> {
    type Row = GatewayGameMode;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = GatewayGameMode> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GatewayGameModesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GatewayGameModesInsertCallbackId {
        GatewayGameModesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GatewayGameModesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GatewayGameModesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GatewayGameModesDeleteCallbackId {
        GatewayGameModesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GatewayGameModesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for GatewayGameModesTableHandle<'ctx> {
    type InsertCallbackId = GatewayGameModesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GatewayGameModesInsertCallbackId {
        GatewayGameModesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GatewayGameModesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for GatewayGameModesTableHandle<'ctx> {
    type DeleteCallbackId = GatewayGameModesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GatewayGameModesDeleteCallbackId {
        GatewayGameModesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GatewayGameModesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct GatewayGameModesUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GatewayGameModesTableHandle<'ctx> {
    type UpdateCallbackId = GatewayGameModesUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GatewayGameModesUpdateCallbackId {
        GatewayGameModesUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GatewayGameModesUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for GatewayGameModesTableHandle<'ctx> {
    type UpdateCallbackId = GatewayGameModesUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GatewayGameModesUpdateCallbackId {
        GatewayGameModesUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GatewayGameModesUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<GatewayGameMode>("gateway_game_modes");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<GatewayGameMode>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<GatewayGameMode>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `GatewayGameMode`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait gateway_game_modesQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `GatewayGameMode`.
    fn gateway_game_modes(&self) -> __sdk::__query_builder::Table<GatewayGameMode>;
}

impl gateway_game_modesQueryTableAccess for __sdk::QueryTableAccessor {
    fn gateway_game_modes(&self) -> __sdk::__query_builder::Table<GatewayGameMode> {
        __sdk::__query_builder::Table::new("gateway_game_modes")
    }
}
