// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::gateway_chat_mode_type::GatewayChatMode;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct GatewayChatPolicy {
    pub gateway_identity: __sdk::Identity,
    pub mode: GatewayChatMode,
}

impl __sdk::InModule for GatewayChatPolicy {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `GatewayChatPolicy`.
///
/// Provides typed access to columns for query building.
pub struct GatewayChatPolicyCols {
    pub gateway_identity: __sdk::__query_builder::Col<GatewayChatPolicy, __sdk::Identity>,
    pub mode: __sdk::__query_builder::Col<GatewayChatPolicy, GatewayChatMode>,
}

impl __sdk::__query_builder::HasCols for GatewayChatPolicy {
    type Cols = GatewayChatPolicyCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        GatewayChatPolicyCols {
            gateway_identity: __sdk::__query_builder::Col::new(table_name, "gateway_identity"),
            mode: __sdk::__query_builder::Col::new(table_name, "mode"),
        }
    }
}

/// Indexed column accessor struct for the table `GatewayChatPolicy`.
///
/// Provides typed access to indexed columns for query building.
pub struct GatewayChatPolicyIxCols {
    pub gateway_identity: __sdk::__query_builder::IxCol<GatewayChatPolicy, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for GatewayChatPolicy {
    type IxCols = GatewayChatPolicyIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        GatewayChatPolicyIxCols {
            gateway_identity: __sdk::__query_builder::IxCol::new(table_name, "gateway_identity"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for GatewayChatPolicy {}
