// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::gateway_chunk_snapshot_type::GatewayChunkSnapshot;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `gateway_chunk_snapshots`.
///
/// Obtain a handle from the [`GatewayChunkSnapshotsTableAccess::gateway_chunk_snapshots`] method on [`super::RemoteTables`],
/// like `ctx.db.gateway_chunk_snapshots()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.gateway_chunk_snapshots().on_insert(...)`.
pub struct GatewayChunkSnapshotsTableHandle<'ctx> {
    imp: __sdk::TableHandle<GatewayChunkSnapshot>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `gateway_chunk_snapshots`.
pub struct GatewayChunkSnapshotsTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for GatewayChunkSnapshotsTableAccessor {
    type Row = GatewayChunkSnapshot;
    type Handle<'db> = GatewayChunkSnapshotsTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.gateway_chunk_snapshots()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `gateway_chunk_snapshots`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GatewayChunkSnapshotsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GatewayChunkSnapshotsTableHandle`], which mediates access to the table `gateway_chunk_snapshots`.
    fn gateway_chunk_snapshots(&self) -> GatewayChunkSnapshotsTableHandle<'_>;
}

impl GatewayChunkSnapshotsTableAccess for super::RemoteTables {
    fn gateway_chunk_snapshots(&self) -> GatewayChunkSnapshotsTableHandle<'_> {
        GatewayChunkSnapshotsTableHandle {
            imp: self
                .imp
                .get_table::<GatewayChunkSnapshot>("gateway_chunk_snapshots"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GatewayChunkSnapshotsInsertCallbackId(__sdk::CallbackId);
pub struct GatewayChunkSnapshotsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for GatewayChunkSnapshotsTableHandle<'ctx> {
    type Row = GatewayChunkSnapshot;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = GatewayChunkSnapshot> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for GatewayChunkSnapshotsTableHandle<'ctx> {
    type Row = GatewayChunkSnapshot;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = GatewayChunkSnapshot> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GatewayChunkSnapshotsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GatewayChunkSnapshotsInsertCallbackId {
        GatewayChunkSnapshotsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GatewayChunkSnapshotsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GatewayChunkSnapshotsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GatewayChunkSnapshotsDeleteCallbackId {
        GatewayChunkSnapshotsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GatewayChunkSnapshotsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for GatewayChunkSnapshotsTableHandle<'ctx> {
    type InsertCallbackId = GatewayChunkSnapshotsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GatewayChunkSnapshotsInsertCallbackId {
        GatewayChunkSnapshotsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GatewayChunkSnapshotsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for GatewayChunkSnapshotsTableHandle<'ctx> {
    type DeleteCallbackId = GatewayChunkSnapshotsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GatewayChunkSnapshotsDeleteCallbackId {
        GatewayChunkSnapshotsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GatewayChunkSnapshotsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct GatewayChunkSnapshotsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GatewayChunkSnapshotsTableHandle<'ctx> {
    type UpdateCallbackId = GatewayChunkSnapshotsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GatewayChunkSnapshotsUpdateCallbackId {
        GatewayChunkSnapshotsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GatewayChunkSnapshotsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for GatewayChunkSnapshotsTableHandle<'ctx> {
    type UpdateCallbackId = GatewayChunkSnapshotsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GatewayChunkSnapshotsUpdateCallbackId {
        GatewayChunkSnapshotsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GatewayChunkSnapshotsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `snapshot_key` unique index on the table `gateway_chunk_snapshots`,
/// which allows point queries on the field of the same name
/// via the [`GatewayChunkSnapshotsSnapshotKeyUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.gateway_chunk_snapshots().snapshot_key().find(...)`.
pub struct GatewayChunkSnapshotsSnapshotKeyUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<GatewayChunkSnapshot, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> GatewayChunkSnapshotsTableHandle<'ctx> {
    /// Get a handle on the `snapshot_key` unique index on the table `gateway_chunk_snapshots`.
    pub fn snapshot_key(&self) -> GatewayChunkSnapshotsSnapshotKeyUnique<'ctx> {
        GatewayChunkSnapshotsSnapshotKeyUnique {
            imp: self.imp.get_unique_constraint::<String>("snapshot_key"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> GatewayChunkSnapshotsSnapshotKeyUnique<'ctx> {
    /// Find the subscribed row whose `snapshot_key` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<GatewayChunkSnapshot> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<GatewayChunkSnapshot>("gateway_chunk_snapshots");
    _table.add_unique_constraint::<String>("snapshot_key", |row| &row.snapshot_key);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<GatewayChunkSnapshot>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<GatewayChunkSnapshot>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `GatewayChunkSnapshot`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait gateway_chunk_snapshotsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `GatewayChunkSnapshot`.
    fn gateway_chunk_snapshots(&self) -> __sdk::__query_builder::Table<GatewayChunkSnapshot>;
}

impl gateway_chunk_snapshotsQueryTableAccess for __sdk::QueryTableAccessor {
    fn gateway_chunk_snapshots(&self) -> __sdk::__query_builder::Table<GatewayChunkSnapshot> {
        __sdk::__query_builder::Table::new("gateway_chunk_snapshots")
    }
}
