// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct GatewayChatMessage {
    pub message_id: u64,
    pub gateway_sequence: u64,
    pub session_uuid: __sdk::Uuid,
    pub player_uuid: __sdk::Uuid,
    pub username: String,
    pub text: String,
    pub verified: bool,
    pub sent_at: __sdk::Timestamp,
}

impl __sdk::InModule for GatewayChatMessage {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `GatewayChatMessage`.
///
/// Provides typed access to columns for query building.
pub struct GatewayChatMessageCols {
    pub message_id: __sdk::__query_builder::Col<GatewayChatMessage, u64>,
    pub gateway_sequence: __sdk::__query_builder::Col<GatewayChatMessage, u64>,
    pub session_uuid: __sdk::__query_builder::Col<GatewayChatMessage, __sdk::Uuid>,
    pub player_uuid: __sdk::__query_builder::Col<GatewayChatMessage, __sdk::Uuid>,
    pub username: __sdk::__query_builder::Col<GatewayChatMessage, String>,
    pub text: __sdk::__query_builder::Col<GatewayChatMessage, String>,
    pub verified: __sdk::__query_builder::Col<GatewayChatMessage, bool>,
    pub sent_at: __sdk::__query_builder::Col<GatewayChatMessage, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for GatewayChatMessage {
    type Cols = GatewayChatMessageCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        GatewayChatMessageCols {
            message_id: __sdk::__query_builder::Col::new(table_name, "message_id"),
            gateway_sequence: __sdk::__query_builder::Col::new(table_name, "gateway_sequence"),
            session_uuid: __sdk::__query_builder::Col::new(table_name, "session_uuid"),
            player_uuid: __sdk::__query_builder::Col::new(table_name, "player_uuid"),
            username: __sdk::__query_builder::Col::new(table_name, "username"),
            text: __sdk::__query_builder::Col::new(table_name, "text"),
            verified: __sdk::__query_builder::Col::new(table_name, "verified"),
            sent_at: __sdk::__query_builder::Col::new(table_name, "sent_at"),
        }
    }
}
