// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct GrantStorageAccessArgs {
    pub player_uuid: __sdk::Uuid,
    pub storage_uuid: __sdk::Uuid,
    pub allowed: bool,
}

impl From<GrantStorageAccessArgs> for super::Reducer {
    fn from(args: GrantStorageAccessArgs) -> Self {
        Self::GrantStorageAccess {
            player_uuid: args.player_uuid,
            storage_uuid: args.storage_uuid,
            allowed: args.allowed,
        }
    }
}

impl __sdk::InModule for GrantStorageAccessArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `grant_storage_access`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait grant_storage_access {
    /// Request that the remote module invoke the reducer `grant_storage_access` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`grant_storage_access:grant_storage_access_then`] to run a callback after the reducer completes.
    fn grant_storage_access(
        &self,
        player_uuid: __sdk::Uuid,
        storage_uuid: __sdk::Uuid,
        allowed: bool,
    ) -> __sdk::Result<()> {
        self.grant_storage_access_then(player_uuid, storage_uuid, allowed, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `grant_storage_access` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn grant_storage_access_then(
        &self,
        player_uuid: __sdk::Uuid,
        storage_uuid: __sdk::Uuid,
        allowed: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl grant_storage_access for super::RemoteReducers {
    fn grant_storage_access_then(
        &self,
        player_uuid: __sdk::Uuid,
        storage_uuid: __sdk::Uuid,
        allowed: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            GrantStorageAccessArgs {
                player_uuid,
                storage_uuid,
                allowed,
            },
            callback,
        )
    }
}
