// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::game_mode_type::GameMode;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct GrantPlayerGameModeArgs {
    pub player_uuid: __sdk::Uuid,
    pub mode: GameMode,
}

impl From<GrantPlayerGameModeArgs> for super::Reducer {
    fn from(args: GrantPlayerGameModeArgs) -> Self {
        Self::GrantPlayerGameMode {
            player_uuid: args.player_uuid,
            mode: args.mode,
        }
    }
}

impl __sdk::InModule for GrantPlayerGameModeArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `grant_player_game_mode`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait grant_player_game_mode {
    /// Request that the remote module invoke the reducer `grant_player_game_mode` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`grant_player_game_mode:grant_player_game_mode_then`] to run a callback after the reducer completes.
    fn grant_player_game_mode(
        &self,
        player_uuid: __sdk::Uuid,
        mode: GameMode,
    ) -> __sdk::Result<()> {
        self.grant_player_game_mode_then(player_uuid, mode, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `grant_player_game_mode` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn grant_player_game_mode_then(
        &self,
        player_uuid: __sdk::Uuid,
        mode: GameMode,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl grant_player_game_mode for super::RemoteReducers {
    fn grant_player_game_mode_then(
        &self,
        player_uuid: __sdk::Uuid,
        mode: GameMode,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(GrantPlayerGameModeArgs { player_uuid, mode }, callback)
    }
}
