// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct HeartbeatSessionsArgs {
    pub session_uuids: Vec<__sdk::Uuid>,
}

impl From<HeartbeatSessionsArgs> for super::Reducer {
    fn from(args: HeartbeatSessionsArgs) -> Self {
        Self::HeartbeatSessions {
            session_uuids: args.session_uuids,
        }
    }
}

impl __sdk::InModule for HeartbeatSessionsArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `heartbeat_sessions`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait heartbeat_sessions {
    /// Request that the remote module invoke the reducer `heartbeat_sessions` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`heartbeat_sessions:heartbeat_sessions_then`] to run a callback after the reducer completes.
    fn heartbeat_sessions(&self, session_uuids: Vec<__sdk::Uuid>) -> __sdk::Result<()> {
        self.heartbeat_sessions_then(session_uuids, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `heartbeat_sessions` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn heartbeat_sessions_then(
        &self,
        session_uuids: Vec<__sdk::Uuid>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl heartbeat_sessions for super::RemoteReducers {
    fn heartbeat_sessions_then(
        &self,
        session_uuids: Vec<__sdk::Uuid>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(HeartbeatSessionsArgs { session_uuids }, callback)
    }
}
