// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct InventorySnapshot {
    pub session_uuid: __sdk::Uuid,
    pub owner_connection: __sdk::ConnectionId,
    pub revision: i32,
    pub selected: u8,
    pub slots: Vec<u8>,
    pub cursor: Vec<u8>,
    pub menu_id: i32,
    pub menu_title: String,
    pub sequence: u64,
    pub creative_allowed: bool,
}

impl __sdk::InModule for InventorySnapshot {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `InventorySnapshot`.
///
/// Provides typed access to columns for query building.
pub struct InventorySnapshotCols {
    pub session_uuid: __sdk::__query_builder::Col<InventorySnapshot, __sdk::Uuid>,
    pub owner_connection: __sdk::__query_builder::Col<InventorySnapshot, __sdk::ConnectionId>,
    pub revision: __sdk::__query_builder::Col<InventorySnapshot, i32>,
    pub selected: __sdk::__query_builder::Col<InventorySnapshot, u8>,
    pub slots: __sdk::__query_builder::Col<InventorySnapshot, Vec<u8>>,
    pub cursor: __sdk::__query_builder::Col<InventorySnapshot, Vec<u8>>,
    pub menu_id: __sdk::__query_builder::Col<InventorySnapshot, i32>,
    pub menu_title: __sdk::__query_builder::Col<InventorySnapshot, String>,
    pub sequence: __sdk::__query_builder::Col<InventorySnapshot, u64>,
    pub creative_allowed: __sdk::__query_builder::Col<InventorySnapshot, bool>,
}

impl __sdk::__query_builder::HasCols for InventorySnapshot {
    type Cols = InventorySnapshotCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        InventorySnapshotCols {
            session_uuid: __sdk::__query_builder::Col::new(table_name, "session_uuid"),
            owner_connection: __sdk::__query_builder::Col::new(table_name, "owner_connection"),
            revision: __sdk::__query_builder::Col::new(table_name, "revision"),
            selected: __sdk::__query_builder::Col::new(table_name, "selected"),
            slots: __sdk::__query_builder::Col::new(table_name, "slots"),
            cursor: __sdk::__query_builder::Col::new(table_name, "cursor"),
            menu_id: __sdk::__query_builder::Col::new(table_name, "menu_id"),
            menu_title: __sdk::__query_builder::Col::new(table_name, "menu_title"),
            sequence: __sdk::__query_builder::Col::new(table_name, "sequence"),
            creative_allowed: __sdk::__query_builder::Col::new(table_name, "creative_allowed"),
        }
    }
}
