// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct InventoryMenu {
    pub session_uuid: __sdk::Uuid,
    pub menu_id: i32,
    pub next_menu_id: i32,
    pub storage_uuid: Option<__sdk::Uuid>,
    pub storage_key: String,
    pub sequence: u64,
    pub last_request: Vec<u8>,
    pub result_revision: i32,
}

impl __sdk::InModule for InventoryMenu {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `InventoryMenu`.
///
/// Provides typed access to columns for query building.
pub struct InventoryMenuCols {
    pub session_uuid: __sdk::__query_builder::Col<InventoryMenu, __sdk::Uuid>,
    pub menu_id: __sdk::__query_builder::Col<InventoryMenu, i32>,
    pub next_menu_id: __sdk::__query_builder::Col<InventoryMenu, i32>,
    pub storage_uuid: __sdk::__query_builder::Col<InventoryMenu, Option<__sdk::Uuid>>,
    pub storage_key: __sdk::__query_builder::Col<InventoryMenu, String>,
    pub sequence: __sdk::__query_builder::Col<InventoryMenu, u64>,
    pub last_request: __sdk::__query_builder::Col<InventoryMenu, Vec<u8>>,
    pub result_revision: __sdk::__query_builder::Col<InventoryMenu, i32>,
}

impl __sdk::__query_builder::HasCols for InventoryMenu {
    type Cols = InventoryMenuCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        InventoryMenuCols {
            session_uuid: __sdk::__query_builder::Col::new(table_name, "session_uuid"),
            menu_id: __sdk::__query_builder::Col::new(table_name, "menu_id"),
            next_menu_id: __sdk::__query_builder::Col::new(table_name, "next_menu_id"),
            storage_uuid: __sdk::__query_builder::Col::new(table_name, "storage_uuid"),
            storage_key: __sdk::__query_builder::Col::new(table_name, "storage_key"),
            sequence: __sdk::__query_builder::Col::new(table_name, "sequence"),
            last_request: __sdk::__query_builder::Col::new(table_name, "last_request"),
            result_revision: __sdk::__query_builder::Col::new(table_name, "result_revision"),
        }
    }
}

/// Indexed column accessor struct for the table `InventoryMenu`.
///
/// Provides typed access to indexed columns for query building.
pub struct InventoryMenuIxCols {
    pub session_uuid: __sdk::__query_builder::IxCol<InventoryMenu, __sdk::Uuid>,
    pub storage_key: __sdk::__query_builder::IxCol<InventoryMenu, String>,
}

impl __sdk::__query_builder::HasIxCols for InventoryMenu {
    type IxCols = InventoryMenuIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        InventoryMenuIxCols {
            session_uuid: __sdk::__query_builder::IxCol::new(table_name, "session_uuid"),
            storage_key: __sdk::__query_builder::IxCol::new(table_name, "storage_key"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for InventoryMenu {}
