// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.10.2 (commit 58d2a40718c59535fd5c267e836d473298eb84d5).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

pub mod add_reducer;
pub mod admin_lease_diagnostic_table;
pub mod admin_lease_diagnostic_type;
pub mod admin_session_diagnostic_type;
pub mod admin_session_diagnostics_table;
pub mod administrator_type;
pub mod advance_login_session_reducer;
pub mod apply_block_action_reducer;
pub mod apply_inventory_request_reducer;
pub mod begin_offline_session_reducer;
pub mod block_action_rate_type;
pub mod block_action_state_type;
pub mod block_override_type;
pub mod change_game_mode_reducer;
pub mod define_simple_storage_reducer;
pub mod end_session_reducer;
pub mod enter_play_session_reducer;
pub mod game_mode_type;
pub mod gateway_block_action_type;
pub mod gateway_block_actions_table;
pub mod gateway_chat_message_type;
pub mod gateway_chat_messages_table;
pub mod gateway_chat_mode_type;
pub mod gateway_chat_policy_type;
pub mod gateway_chat_sequence_type;
pub mod gateway_chunk_snapshot_type;
pub mod gateway_chunk_snapshots_table;
pub mod gateway_chunk_state_type;
pub mod gateway_game_mode_type;
pub mod gateway_game_modes_table;
pub mod gateway_inventory_snapshots_table;
pub mod gateway_player_state_table;
pub mod gateway_player_state_type;
pub mod gateway_profiles_table;
pub mod gateway_sessions_table;
pub mod gateway_type;
pub mod gateway_world_player_type;
pub mod gateway_world_players_table;
pub mod grant_inventory_permission_reducer;
pub mod grant_player_game_mode_reducer;
pub mod grant_storage_access_reducer;
pub mod heartbeat_sessions_reducer;
pub mod identity_kind_type;
pub mod initialize_player_inventory_reducer;
pub mod inventory_menu_type;
pub mod inventory_permission_type;
pub mod inventory_snapshot_type;
pub mod my_gateway_table;
pub mod person_table;
pub mod person_type;
pub mod player_chat_message_type;
pub mod player_chat_rate_type;
pub mod player_game_mode_type;
pub mod player_inventory_type;
pub mod player_pose_type;
pub mod player_pose_update_type;
pub mod player_profile_type;
pub mod player_session_type;
pub mod player_vitals_type;
pub mod register_gateway_reducer;
pub mod request_player_respawn_reducer;
pub mod revoke_gateway_reducer;
pub mod say_hello_reducer;
pub mod send_chat_reducer;
pub mod session_entity_type;
pub mod session_lease_cleanup_type;
pub mod session_lease_metrics_type;
pub mod session_phase_type;
pub mod set_gateway_chat_mode_reducer;
pub mod simple_storage_type;
pub mod storage_access_type;
pub mod update_player_states_reducer;
pub mod update_player_vitals_reducer;
pub mod update_world_interest_reducer;
pub mod world_interest_type;

pub use add_reducer::add;
pub use admin_lease_diagnostic_table::*;
pub use admin_lease_diagnostic_type::AdminLeaseDiagnostic;
pub use admin_session_diagnostic_type::AdminSessionDiagnostic;
pub use admin_session_diagnostics_table::*;
pub use administrator_type::Administrator;
pub use advance_login_session_reducer::advance_login_session;
pub use apply_block_action_reducer::apply_block_action;
pub use apply_inventory_request_reducer::apply_inventory_request;
pub use begin_offline_session_reducer::begin_offline_session;
pub use block_action_rate_type::BlockActionRate;
pub use block_action_state_type::BlockActionState;
pub use block_override_type::BlockOverride;
pub use change_game_mode_reducer::change_game_mode;
pub use define_simple_storage_reducer::define_simple_storage;
pub use end_session_reducer::end_session;
pub use enter_play_session_reducer::enter_play_session;
pub use game_mode_type::GameMode;
pub use gateway_block_action_type::GatewayBlockAction;
pub use gateway_block_actions_table::*;
pub use gateway_chat_message_type::GatewayChatMessage;
pub use gateway_chat_messages_table::*;
pub use gateway_chat_mode_type::GatewayChatMode;
pub use gateway_chat_policy_type::GatewayChatPolicy;
pub use gateway_chat_sequence_type::GatewayChatSequence;
pub use gateway_chunk_snapshot_type::GatewayChunkSnapshot;
pub use gateway_chunk_snapshots_table::*;
pub use gateway_chunk_state_type::GatewayChunkState;
pub use gateway_game_mode_type::GatewayGameMode;
pub use gateway_game_modes_table::*;
pub use gateway_inventory_snapshots_table::*;
pub use gateway_player_state_table::*;
pub use gateway_player_state_type::GatewayPlayerState;
pub use gateway_profiles_table::*;
pub use gateway_sessions_table::*;
pub use gateway_type::Gateway;
pub use gateway_world_player_type::GatewayWorldPlayer;
pub use gateway_world_players_table::*;
pub use grant_inventory_permission_reducer::grant_inventory_permission;
pub use grant_player_game_mode_reducer::grant_player_game_mode;
pub use grant_storage_access_reducer::grant_storage_access;
pub use heartbeat_sessions_reducer::heartbeat_sessions;
pub use identity_kind_type::IdentityKind;
pub use initialize_player_inventory_reducer::initialize_player_inventory;
pub use inventory_menu_type::InventoryMenu;
pub use inventory_permission_type::InventoryPermission;
pub use inventory_snapshot_type::InventorySnapshot;
pub use my_gateway_table::*;
pub use person_table::*;
pub use person_type::Person;
pub use player_chat_message_type::PlayerChatMessage;
pub use player_chat_rate_type::PlayerChatRate;
pub use player_game_mode_type::PlayerGameMode;
pub use player_inventory_type::PlayerInventory;
pub use player_pose_type::PlayerPose;
pub use player_pose_update_type::PlayerPoseUpdate;
pub use player_profile_type::PlayerProfile;
pub use player_session_type::PlayerSession;
pub use player_vitals_type::PlayerVitals;
pub use register_gateway_reducer::register_gateway;
pub use request_player_respawn_reducer::request_player_respawn;
pub use revoke_gateway_reducer::revoke_gateway;
pub use say_hello_reducer::say_hello;
pub use send_chat_reducer::send_chat;
pub use session_entity_type::SessionEntity;
pub use session_lease_cleanup_type::SessionLeaseCleanup;
pub use session_lease_metrics_type::SessionLeaseMetrics;
pub use session_phase_type::SessionPhase;
pub use set_gateway_chat_mode_reducer::set_gateway_chat_mode;
pub use simple_storage_type::SimpleStorage;
pub use storage_access_type::StorageAccess;
pub use update_player_states_reducer::update_player_states;
pub use update_player_vitals_reducer::update_player_vitals;
pub use update_world_interest_reducer::update_world_interest;
pub use world_interest_type::WorldInterest;

#[derive(Clone, PartialEq, Debug)]

/// One of the reducers defined by this module.
///
/// Contained within a [`__sdk::ReducerEvent`] in [`EventContext`]s for reducer events
/// to indicate which reducer caused the event.

pub enum Reducer {
    Add {
        name: String,
    },
    AdvanceLoginSession {
        session_uuid: __sdk::Uuid,
    },
    ApplyBlockAction {
        session_uuid: __sdk::Uuid,
        sequence: u64,
        x: i32,
        y: i32,
        z: i32,
        expected_state: u32,
        place: bool,
    },
    ApplyInventoryRequest {
        session_uuid: __sdk::Uuid,
        sequence: u64,
        payload: Vec<u8>,
    },
    BeginOfflineSession {
        session_uuid: __sdk::Uuid,
        username: String,
    },
    ChangeGameMode {
        session_uuid: __sdk::Uuid,
        mode: GameMode,
    },
    DefineSimpleStorage {
        storage_uuid: __sdk::Uuid,
        title: String,
    },
    EndSession {
        session_uuid: __sdk::Uuid,
    },
    EnterPlaySession {
        session_uuid: __sdk::Uuid,
    },
    GrantInventoryPermission {
        player_uuid: __sdk::Uuid,
        creative: bool,
    },
    GrantPlayerGameMode {
        player_uuid: __sdk::Uuid,
        mode: GameMode,
    },
    GrantStorageAccess {
        player_uuid: __sdk::Uuid,
        storage_uuid: __sdk::Uuid,
        allowed: bool,
    },
    HeartbeatSessions {
        session_uuids: Vec<__sdk::Uuid>,
    },
    InitializePlayerInventory {
        session_uuid: __sdk::Uuid,
    },
    RegisterGateway {
        identity: __sdk::Identity,
    },
    RequestPlayerRespawn {
        session_uuid: __sdk::Uuid,
    },
    RevokeGateway {
        identity: __sdk::Identity,
    },
    SayHello,
    SendChat {
        session_uuid: __sdk::Uuid,
        text: String,
    },
    SetGatewayChatMode {
        gateway_identity: __sdk::Identity,
        mode: GatewayChatMode,
    },
    UpdatePlayerStates {
        updates: Vec<PlayerPoseUpdate>,
    },
    UpdatePlayerVitals {
        session_uuid: __sdk::Uuid,
        health: u8,
        food: u8,
        dead: bool,
        expected_revision: u64,
    },
    UpdateWorldInterest {
        session_uuid: __sdk::Uuid,
        chunk_x: i32,
        chunk_z: i32,
        radius: u8,
    },
}

impl __sdk::InModule for Reducer {
    type Module = RemoteModule;
}

impl __sdk::Reducer for Reducer {
    fn reducer_name(&self) -> &'static str {
        match self {
            Reducer::Add { .. } => "add",
            Reducer::AdvanceLoginSession { .. } => "advance_login_session",
            Reducer::ApplyBlockAction { .. } => "apply_block_action",
            Reducer::ApplyInventoryRequest { .. } => "apply_inventory_request",
            Reducer::BeginOfflineSession { .. } => "begin_offline_session",
            Reducer::ChangeGameMode { .. } => "change_game_mode",
            Reducer::DefineSimpleStorage { .. } => "define_simple_storage",
            Reducer::EndSession { .. } => "end_session",
            Reducer::EnterPlaySession { .. } => "enter_play_session",
            Reducer::GrantInventoryPermission { .. } => "grant_inventory_permission",
            Reducer::GrantPlayerGameMode { .. } => "grant_player_game_mode",
            Reducer::GrantStorageAccess { .. } => "grant_storage_access",
            Reducer::HeartbeatSessions { .. } => "heartbeat_sessions",
            Reducer::InitializePlayerInventory { .. } => "initialize_player_inventory",
            Reducer::RegisterGateway { .. } => "register_gateway",
            Reducer::RequestPlayerRespawn { .. } => "request_player_respawn",
            Reducer::RevokeGateway { .. } => "revoke_gateway",
            Reducer::SayHello => "say_hello",
            Reducer::SendChat { .. } => "send_chat",
            Reducer::SetGatewayChatMode { .. } => "set_gateway_chat_mode",
            Reducer::UpdatePlayerStates { .. } => "update_player_states",
            Reducer::UpdatePlayerVitals { .. } => "update_player_vitals",
            Reducer::UpdateWorldInterest { .. } => "update_world_interest",
            _ => unreachable!(),
        }
    }
    #[allow(clippy::clone_on_copy)]
    fn args_bsatn(&self) -> Result<Vec<u8>, __sats::bsatn::EncodeError> {
        match self {
            Reducer::Add { name } => {
                __sats::bsatn::to_vec(&add_reducer::AddArgs { name: name.clone() })
            }
            Reducer::AdvanceLoginSession { session_uuid } => {
                __sats::bsatn::to_vec(&advance_login_session_reducer::AdvanceLoginSessionArgs {
                    session_uuid: session_uuid.clone(),
                })
            }
            Reducer::ApplyBlockAction {
                session_uuid,
                sequence,
                x,
                y,
                z,
                expected_state,
                place,
            } => __sats::bsatn::to_vec(&apply_block_action_reducer::ApplyBlockActionArgs {
                session_uuid: session_uuid.clone(),
                sequence: sequence.clone(),
                x: x.clone(),
                y: y.clone(),
                z: z.clone(),
                expected_state: expected_state.clone(),
                place: place.clone(),
            }),
            Reducer::ApplyInventoryRequest {
                session_uuid,
                sequence,
                payload,
            } => __sats::bsatn::to_vec(
                &apply_inventory_request_reducer::ApplyInventoryRequestArgs {
                    session_uuid: session_uuid.clone(),
                    sequence: sequence.clone(),
                    payload: payload.clone(),
                },
            ),
            Reducer::BeginOfflineSession {
                session_uuid,
                username,
            } => __sats::bsatn::to_vec(&begin_offline_session_reducer::BeginOfflineSessionArgs {
                session_uuid: session_uuid.clone(),
                username: username.clone(),
            }),
            Reducer::ChangeGameMode { session_uuid, mode } => {
                __sats::bsatn::to_vec(&change_game_mode_reducer::ChangeGameModeArgs {
                    session_uuid: session_uuid.clone(),
                    mode: mode.clone(),
                })
            }
            Reducer::DefineSimpleStorage {
                storage_uuid,
                title,
            } => __sats::bsatn::to_vec(&define_simple_storage_reducer::DefineSimpleStorageArgs {
                storage_uuid: storage_uuid.clone(),
                title: title.clone(),
            }),
            Reducer::EndSession { session_uuid } => {
                __sats::bsatn::to_vec(&end_session_reducer::EndSessionArgs {
                    session_uuid: session_uuid.clone(),
                })
            }
            Reducer::EnterPlaySession { session_uuid } => {
                __sats::bsatn::to_vec(&enter_play_session_reducer::EnterPlaySessionArgs {
                    session_uuid: session_uuid.clone(),
                })
            }
            Reducer::GrantInventoryPermission {
                player_uuid,
                creative,
            } => __sats::bsatn::to_vec(
                &grant_inventory_permission_reducer::GrantInventoryPermissionArgs {
                    player_uuid: player_uuid.clone(),
                    creative: creative.clone(),
                },
            ),
            Reducer::GrantPlayerGameMode { player_uuid, mode } => {
                __sats::bsatn::to_vec(&grant_player_game_mode_reducer::GrantPlayerGameModeArgs {
                    player_uuid: player_uuid.clone(),
                    mode: mode.clone(),
                })
            }
            Reducer::GrantStorageAccess {
                player_uuid,
                storage_uuid,
                allowed,
            } => __sats::bsatn::to_vec(&grant_storage_access_reducer::GrantStorageAccessArgs {
                player_uuid: player_uuid.clone(),
                storage_uuid: storage_uuid.clone(),
                allowed: allowed.clone(),
            }),
            Reducer::HeartbeatSessions { session_uuids } => {
                __sats::bsatn::to_vec(&heartbeat_sessions_reducer::HeartbeatSessionsArgs {
                    session_uuids: session_uuids.clone(),
                })
            }
            Reducer::InitializePlayerInventory { session_uuid } => __sats::bsatn::to_vec(
                &initialize_player_inventory_reducer::InitializePlayerInventoryArgs {
                    session_uuid: session_uuid.clone(),
                },
            ),
            Reducer::RegisterGateway { identity } => {
                __sats::bsatn::to_vec(&register_gateway_reducer::RegisterGatewayArgs {
                    identity: identity.clone(),
                })
            }
            Reducer::RequestPlayerRespawn { session_uuid } => {
                __sats::bsatn::to_vec(&request_player_respawn_reducer::RequestPlayerRespawnArgs {
                    session_uuid: session_uuid.clone(),
                })
            }
            Reducer::RevokeGateway { identity } => {
                __sats::bsatn::to_vec(&revoke_gateway_reducer::RevokeGatewayArgs {
                    identity: identity.clone(),
                })
            }
            Reducer::SayHello => __sats::bsatn::to_vec(&say_hello_reducer::SayHelloArgs {}),
            Reducer::SendChat { session_uuid, text } => {
                __sats::bsatn::to_vec(&send_chat_reducer::SendChatArgs {
                    session_uuid: session_uuid.clone(),
                    text: text.clone(),
                })
            }
            Reducer::SetGatewayChatMode {
                gateway_identity,
                mode,
            } => __sats::bsatn::to_vec(&set_gateway_chat_mode_reducer::SetGatewayChatModeArgs {
                gateway_identity: gateway_identity.clone(),
                mode: mode.clone(),
            }),
            Reducer::UpdatePlayerStates { updates } => {
                __sats::bsatn::to_vec(&update_player_states_reducer::UpdatePlayerStatesArgs {
                    updates: updates.clone(),
                })
            }
            Reducer::UpdatePlayerVitals {
                session_uuid,
                health,
                food,
                dead,
                expected_revision,
            } => __sats::bsatn::to_vec(&update_player_vitals_reducer::UpdatePlayerVitalsArgs {
                session_uuid: session_uuid.clone(),
                health: health.clone(),
                food: food.clone(),
                dead: dead.clone(),
                expected_revision: expected_revision.clone(),
            }),
            Reducer::UpdateWorldInterest {
                session_uuid,
                chunk_x,
                chunk_z,
                radius,
            } => __sats::bsatn::to_vec(&update_world_interest_reducer::UpdateWorldInterestArgs {
                session_uuid: session_uuid.clone(),
                chunk_x: chunk_x.clone(),
                chunk_z: chunk_z.clone(),
                radius: radius.clone(),
            }),
            _ => unreachable!(),
        }
    }
}

#[derive(Default, Debug)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct DbUpdate {
    admin_lease_diagnostic: __sdk::TableUpdate<AdminLeaseDiagnostic>,
    admin_session_diagnostics: __sdk::TableUpdate<AdminSessionDiagnostic>,
    gateway_block_actions: __sdk::TableUpdate<GatewayBlockAction>,
    gateway_chat_messages: __sdk::TableUpdate<GatewayChatMessage>,
    gateway_chunk_snapshots: __sdk::TableUpdate<GatewayChunkSnapshot>,
    gateway_game_modes: __sdk::TableUpdate<GatewayGameMode>,
    gateway_inventory_snapshots: __sdk::TableUpdate<InventorySnapshot>,
    gateway_player_state: __sdk::TableUpdate<GatewayPlayerState>,
    gateway_profiles: __sdk::TableUpdate<PlayerProfile>,
    gateway_sessions: __sdk::TableUpdate<PlayerSession>,
    gateway_world_players: __sdk::TableUpdate<GatewayWorldPlayer>,
    my_gateway: __sdk::TableUpdate<Gateway>,
    person: __sdk::TableUpdate<Person>,
}

impl TryFrom<__ws::v2::TransactionUpdate> for DbUpdate {
    type Error = __sdk::Error;
    fn try_from(raw: __ws::v2::TransactionUpdate) -> Result<Self, Self::Error> {
        let mut db_update = DbUpdate::default();
        for table_update in __sdk::transaction_update_iter_table_updates(raw) {
            match &table_update.table_name[..] {
                "admin_lease_diagnostic" => db_update.admin_lease_diagnostic.append(
                    admin_lease_diagnostic_table::parse_table_update(table_update)?,
                ),
                "admin_session_diagnostics" => db_update.admin_session_diagnostics.append(
                    admin_session_diagnostics_table::parse_table_update(table_update)?,
                ),
                "gateway_block_actions" => db_update.gateway_block_actions.append(
                    gateway_block_actions_table::parse_table_update(table_update)?,
                ),
                "gateway_chat_messages" => db_update.gateway_chat_messages.append(
                    gateway_chat_messages_table::parse_table_update(table_update)?,
                ),
                "gateway_chunk_snapshots" => db_update.gateway_chunk_snapshots.append(
                    gateway_chunk_snapshots_table::parse_table_update(table_update)?,
                ),
                "gateway_game_modes" => db_update
                    .gateway_game_modes
                    .append(gateway_game_modes_table::parse_table_update(table_update)?),
                "gateway_inventory_snapshots" => db_update.gateway_inventory_snapshots.append(
                    gateway_inventory_snapshots_table::parse_table_update(table_update)?,
                ),
                "gateway_player_state" => db_update.gateway_player_state.append(
                    gateway_player_state_table::parse_table_update(table_update)?,
                ),
                "gateway_profiles" => db_update
                    .gateway_profiles
                    .append(gateway_profiles_table::parse_table_update(table_update)?),
                "gateway_sessions" => db_update
                    .gateway_sessions
                    .append(gateway_sessions_table::parse_table_update(table_update)?),
                "gateway_world_players" => db_update.gateway_world_players.append(
                    gateway_world_players_table::parse_table_update(table_update)?,
                ),
                "my_gateway" => db_update
                    .my_gateway
                    .append(my_gateway_table::parse_table_update(table_update)?),
                "person" => db_update
                    .person
                    .append(person_table::parse_table_update(table_update)?),

                unknown => {
                    return Err(__sdk::InternalError::unknown_name(
                        "table",
                        unknown,
                        "DatabaseUpdate",
                    )
                    .into());
                }
            }
        }
        Ok(db_update)
    }
}

impl __sdk::InModule for DbUpdate {
    type Module = RemoteModule;
}

impl __sdk::DbUpdate for DbUpdate {
    fn apply_to_client_cache(
        &self,
        cache: &mut __sdk::ClientCache<RemoteModule>,
    ) -> AppliedDiff<'_> {
        let mut diff = AppliedDiff::default();

        diff.person = cache.apply_diff_to_table::<Person>("person", &self.person);
        diff.admin_lease_diagnostic = cache
            .apply_diff_to_table::<AdminLeaseDiagnostic>(
                "admin_lease_diagnostic",
                &self.admin_lease_diagnostic,
            )
            .with_updates_by_pk(|row| &row.id);
        diff.admin_session_diagnostics = cache
            .apply_diff_to_table::<AdminSessionDiagnostic>(
                "admin_session_diagnostics",
                &self.admin_session_diagnostics,
            )
            .with_updates_by_pk(|row| &row.session_uuid);
        diff.gateway_block_actions = cache
            .apply_diff_to_table::<GatewayBlockAction>(
                "gateway_block_actions",
                &self.gateway_block_actions,
            )
            .with_updates_by_pk(|row| &row.session_uuid);
        diff.gateway_chat_messages = cache
            .apply_diff_to_table::<GatewayChatMessage>(
                "gateway_chat_messages",
                &self.gateway_chat_messages,
            )
            .with_updates_by_pk(|row| &row.message_id);
        diff.gateway_chunk_snapshots = cache
            .apply_diff_to_table::<GatewayChunkSnapshot>(
                "gateway_chunk_snapshots",
                &self.gateway_chunk_snapshots,
            )
            .with_updates_by_pk(|row| &row.snapshot_key);
        diff.gateway_game_modes = cache
            .apply_diff_to_table::<GatewayGameMode>("gateway_game_modes", &self.gateway_game_modes)
            .with_updates_by_pk(|row| &row.session_uuid);
        diff.gateway_inventory_snapshots = cache
            .apply_diff_to_table::<InventorySnapshot>(
                "gateway_inventory_snapshots",
                &self.gateway_inventory_snapshots,
            )
            .with_updates_by_pk(|row| &row.session_uuid);
        diff.gateway_player_state = cache
            .apply_diff_to_table::<GatewayPlayerState>(
                "gateway_player_state",
                &self.gateway_player_state,
            )
            .with_updates_by_pk(|row| &row.session_uuid);
        diff.gateway_profiles = cache
            .apply_diff_to_table::<PlayerProfile>("gateway_profiles", &self.gateway_profiles)
            .with_updates_by_pk(|row| &row.player_uuid);
        diff.gateway_sessions = cache
            .apply_diff_to_table::<PlayerSession>("gateway_sessions", &self.gateway_sessions)
            .with_updates_by_pk(|row| &row.session_uuid);
        diff.gateway_world_players = cache
            .apply_diff_to_table::<GatewayWorldPlayer>(
                "gateway_world_players",
                &self.gateway_world_players,
            )
            .with_updates_by_pk(|row| &row.session_uuid);
        diff.my_gateway = cache
            .apply_diff_to_table::<Gateway>("my_gateway", &self.my_gateway)
            .with_updates_by_pk(|row| &row.identity);

        diff
    }
    fn parse_initial_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "admin_lease_diagnostic" => db_update
                    .admin_lease_diagnostic
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "admin_session_diagnostics" => db_update
                    .admin_session_diagnostics
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "gateway_block_actions" => db_update
                    .gateway_block_actions
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "gateway_chat_messages" => db_update
                    .gateway_chat_messages
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "gateway_chunk_snapshots" => db_update
                    .gateway_chunk_snapshots
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "gateway_game_modes" => db_update
                    .gateway_game_modes
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "gateway_inventory_snapshots" => db_update
                    .gateway_inventory_snapshots
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "gateway_player_state" => db_update
                    .gateway_player_state
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "gateway_profiles" => db_update
                    .gateway_profiles
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "gateway_sessions" => db_update
                    .gateway_sessions
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "gateway_world_players" => db_update
                    .gateway_world_players
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "my_gateway" => db_update
                    .my_gateway
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "person" => db_update
                    .person
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
    fn parse_unsubscribe_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "admin_lease_diagnostic" => db_update
                    .admin_lease_diagnostic
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "admin_session_diagnostics" => db_update
                    .admin_session_diagnostics
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "gateway_block_actions" => db_update
                    .gateway_block_actions
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "gateway_chat_messages" => db_update
                    .gateway_chat_messages
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "gateway_chunk_snapshots" => db_update
                    .gateway_chunk_snapshots
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "gateway_game_modes" => db_update
                    .gateway_game_modes
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "gateway_inventory_snapshots" => db_update
                    .gateway_inventory_snapshots
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "gateway_player_state" => db_update
                    .gateway_player_state
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "gateway_profiles" => db_update
                    .gateway_profiles
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "gateway_sessions" => db_update
                    .gateway_sessions
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "gateway_world_players" => db_update
                    .gateway_world_players
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "my_gateway" => db_update
                    .my_gateway
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "person" => db_update
                    .person
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct AppliedDiff<'r> {
    admin_lease_diagnostic: __sdk::TableAppliedDiff<'r, AdminLeaseDiagnostic>,
    admin_session_diagnostics: __sdk::TableAppliedDiff<'r, AdminSessionDiagnostic>,
    gateway_block_actions: __sdk::TableAppliedDiff<'r, GatewayBlockAction>,
    gateway_chat_messages: __sdk::TableAppliedDiff<'r, GatewayChatMessage>,
    gateway_chunk_snapshots: __sdk::TableAppliedDiff<'r, GatewayChunkSnapshot>,
    gateway_game_modes: __sdk::TableAppliedDiff<'r, GatewayGameMode>,
    gateway_inventory_snapshots: __sdk::TableAppliedDiff<'r, InventorySnapshot>,
    gateway_player_state: __sdk::TableAppliedDiff<'r, GatewayPlayerState>,
    gateway_profiles: __sdk::TableAppliedDiff<'r, PlayerProfile>,
    gateway_sessions: __sdk::TableAppliedDiff<'r, PlayerSession>,
    gateway_world_players: __sdk::TableAppliedDiff<'r, GatewayWorldPlayer>,
    my_gateway: __sdk::TableAppliedDiff<'r, Gateway>,
    person: __sdk::TableAppliedDiff<'r, Person>,
    __unused: std::marker::PhantomData<&'r ()>,
}

impl __sdk::InModule for AppliedDiff<'_> {
    type Module = RemoteModule;
}

impl<'r> __sdk::AppliedDiff<'r> for AppliedDiff<'r> {
    fn invoke_row_callbacks(
        &self,
        event: &EventContext,
        callbacks: &mut __sdk::DbCallbacks<RemoteModule>,
    ) {
        callbacks.invoke_table_row_callbacks::<AdminLeaseDiagnostic>(
            "admin_lease_diagnostic",
            &self.admin_lease_diagnostic,
            event,
        );
        callbacks.invoke_table_row_callbacks::<AdminSessionDiagnostic>(
            "admin_session_diagnostics",
            &self.admin_session_diagnostics,
            event,
        );
        callbacks.invoke_table_row_callbacks::<GatewayBlockAction>(
            "gateway_block_actions",
            &self.gateway_block_actions,
            event,
        );
        callbacks.invoke_table_row_callbacks::<GatewayChatMessage>(
            "gateway_chat_messages",
            &self.gateway_chat_messages,
            event,
        );
        callbacks.invoke_table_row_callbacks::<GatewayChunkSnapshot>(
            "gateway_chunk_snapshots",
            &self.gateway_chunk_snapshots,
            event,
        );
        callbacks.invoke_table_row_callbacks::<GatewayGameMode>(
            "gateway_game_modes",
            &self.gateway_game_modes,
            event,
        );
        callbacks.invoke_table_row_callbacks::<InventorySnapshot>(
            "gateway_inventory_snapshots",
            &self.gateway_inventory_snapshots,
            event,
        );
        callbacks.invoke_table_row_callbacks::<GatewayPlayerState>(
            "gateway_player_state",
            &self.gateway_player_state,
            event,
        );
        callbacks.invoke_table_row_callbacks::<PlayerProfile>(
            "gateway_profiles",
            &self.gateway_profiles,
            event,
        );
        callbacks.invoke_table_row_callbacks::<PlayerSession>(
            "gateway_sessions",
            &self.gateway_sessions,
            event,
        );
        callbacks.invoke_table_row_callbacks::<GatewayWorldPlayer>(
            "gateway_world_players",
            &self.gateway_world_players,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Gateway>("my_gateway", &self.my_gateway, event);
        callbacks.invoke_table_row_callbacks::<Person>("person", &self.person, event);
    }
}

#[doc(hidden)]
#[derive(Debug)]
pub struct RemoteModule;

impl __sdk::InModule for RemoteModule {
    type Module = Self;
}

/// The `reducers` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each reducer defined by the module.
pub struct RemoteReducers {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteReducers {
    type Module = RemoteModule;
}

/// The `procedures` field of [`DbConnection`] and other [`DbContext`] types,
/// with methods provided by extension traits for each procedure defined by the module.
pub struct RemoteProcedures {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteProcedures {
    type Module = RemoteModule;
}

/// The `db` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each table defined by the module.
pub struct RemoteTables {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteTables {
    type Module = RemoteModule;
}

/// A connection to a remote module, including a materialized view of a subset of the database.
///
/// Connect to a remote module by calling [`DbConnection::builder`]
/// and using the [`__sdk::DbConnectionBuilder`] builder-pattern constructor.
///
/// You must explicitly advance the connection by calling any one of:
///
/// - [`DbConnection::frame_tick`].
#[cfg_attr(not(target_arch = "wasm32"), doc = "- [`DbConnection::run_threaded`].")]
#[cfg_attr(
    target_arch = "wasm32",
    doc = "- [`DbConnection::run_background_task`]."
)]
/// - [`DbConnection::run_async`].
/// - [`DbConnection::advance_one_message`].
#[cfg_attr(
    not(target_arch = "wasm32"),
    doc = "- [`DbConnection::advance_one_message_blocking`]."
)]
/// - [`DbConnection::advance_one_message_async`].
///
/// Which of these methods you should call depends on the specific needs of your application,
/// but you must call one of them, or else the connection will never progress.
pub struct DbConnection {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    #[doc(hidden)]

    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,

    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for DbConnection {
    type Module = RemoteModule;
}

impl __sdk::DbContext for DbConnection {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl DbConnection {
    /// Builder-pattern constructor for a connection to a remote module.
    ///
    /// See [`__sdk::DbConnectionBuilder`] for required and optional configuration for the new connection.
    pub fn builder() -> __sdk::DbConnectionBuilder<RemoteModule> {
        __sdk::DbConnectionBuilder::new()
    }

    /// If any WebSocket messages are waiting, process one of them.
    ///
    /// Returns `true` if a message was processed, or `false` if the queue is empty.
    /// Callers should invoke this message in a loop until it returns `false`
    /// or for as much time is available to process messages.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::frame_tick`] each frame
    /// to fully exhaust the queue whenever time is available.
    pub fn advance_one_message(&self) -> __sdk::Result<bool> {
        self.imp.advance_one_message()
    }

    /// Process one WebSocket message, potentially blocking the current thread until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_threaded`] to spawn a thread
    /// which advances the connection automatically.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn advance_one_message_blocking(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_blocking()
    }

    /// Process one WebSocket message, `await`ing until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_async`] to run an `async` loop
    /// which advances the connection when polled.
    pub async fn advance_one_message_async(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_async().await
    }

    /// Process all WebSocket messages waiting in the queue,
    /// then return without `await`ing or blocking the current thread.
    pub fn frame_tick(&self) -> __sdk::Result<()> {
        self.imp.frame_tick()
    }

    /// Spawn a thread which processes WebSocket messages as they are received.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn run_threaded(&self) -> std::thread::JoinHandle<()> {
        self.imp.run_threaded()
    }

    /// Spawn a background task which processes WebSocket messages as they are received.
    #[cfg(target_arch = "wasm32")]
    pub fn run_background_task(&self) {
        self.imp.run_background_task()
    }

    /// Run an `async` loop which processes WebSocket messages when polled.
    pub async fn run_async(&self) -> __sdk::Result<()> {
        self.imp.run_async().await
    }
}

impl __sdk::DbConnection for DbConnection {
    fn new(imp: __sdk::DbContextImpl<RemoteModule>) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

/// A handle on a subscribed query.
// TODO: Document this better after implementing the new subscription API.
#[derive(Clone)]
pub struct SubscriptionHandle {
    imp: __sdk::SubscriptionHandleImpl<RemoteModule>,
}

impl __sdk::InModule for SubscriptionHandle {
    type Module = RemoteModule;
}

impl __sdk::SubscriptionHandle for SubscriptionHandle {
    fn new(imp: __sdk::SubscriptionHandleImpl<RemoteModule>) -> Self {
        Self { imp }
    }

    /// Returns true if this subscription has been terminated due to an unsubscribe call or an error.
    fn is_ended(&self) -> bool {
        self.imp.is_ended()
    }

    /// Returns true if this subscription has been applied and has not yet been unsubscribed.
    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    /// Unsubscribe from the query controlled by this `SubscriptionHandle`,
    /// then run `on_end` when its rows are removed from the client cache.
    fn unsubscribe_then(self, on_end: __sdk::OnEndedCallback<RemoteModule>) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(Some(on_end))
    }

    fn unsubscribe(self) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(None)
    }
}

/// Alias trait for a [`__sdk::DbContext`] connected to this module,
/// with that trait's associated types bounded to this module's concrete types.
///
/// Users can use this trait as a boundary on definitions which should accept
/// either a [`DbConnection`] or an [`EventContext`] and operate on either.
pub trait RemoteDbContext:
    __sdk::DbContext<
    DbView = RemoteTables,
    Reducers = RemoteReducers,
    SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
>
{
}
impl<
        Ctx: __sdk::DbContext<
            DbView = RemoteTables,
            Reducers = RemoteReducers,
            SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
        >,
    > RemoteDbContext for Ctx
{
}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Event`],
/// passed to [`__sdk::Table::on_insert`], [`__sdk::Table::on_delete`] and [`__sdk::TableWithPrimaryKey::on_update`] callbacks.
pub struct EventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::Event<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for EventContext {
    type Event = __sdk::Event<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for EventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for EventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::EventContext for EventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::ReducerEvent`],
/// passed to on-reducer callbacks.
pub struct ReducerEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::ReducerEvent<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ReducerEventContext {
    type Event = __sdk::ReducerEvent<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ReducerEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ReducerEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ReducerEventContext for ReducerEventContext {}

/// An [`__sdk::DbContext`] passed to procedure callbacks.
pub struct ProcedureEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ProcedureEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for ProcedureEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ProcedureEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ProcedureEventContext for ProcedureEventContext {}

/// An [`__sdk::DbContext`] passed to [`__sdk::SubscriptionBuilder::on_applied`] and [`SubscriptionHandle::unsubscribe_then`] callbacks.
pub struct SubscriptionEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for SubscriptionEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for SubscriptionEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for SubscriptionEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::SubscriptionEventContext for SubscriptionEventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Error`],
/// passed to [`__sdk::DbConnectionBuilder::on_disconnect`], [`__sdk::DbConnectionBuilder::on_connect_error`] and [`__sdk::SubscriptionBuilder::on_error`] callbacks.
pub struct ErrorContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: Option<__sdk::Error>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ErrorContext {
    type Event = Option<__sdk::Error>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ErrorContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ErrorContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ErrorContext for ErrorContext {}

impl __sdk::SpacetimeModule for RemoteModule {
    type DbConnection = DbConnection;
    type EventContext = EventContext;
    type ReducerEventContext = ReducerEventContext;
    type ProcedureEventContext = ProcedureEventContext;
    type SubscriptionEventContext = SubscriptionEventContext;
    type ErrorContext = ErrorContext;
    type Reducer = Reducer;
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type DbUpdate = DbUpdate;
    type AppliedDiff<'r> = AppliedDiff<'r>;
    type SubscriptionHandle = SubscriptionHandle;
    type QueryBuilder = __sdk::QueryBuilder;

    fn register_tables(client_cache: &mut __sdk::ClientCache<Self>) {
        admin_lease_diagnostic_table::register_table(client_cache);
        admin_session_diagnostics_table::register_table(client_cache);
        gateway_block_actions_table::register_table(client_cache);
        gateway_chat_messages_table::register_table(client_cache);
        gateway_chunk_snapshots_table::register_table(client_cache);
        gateway_game_modes_table::register_table(client_cache);
        gateway_inventory_snapshots_table::register_table(client_cache);
        gateway_player_state_table::register_table(client_cache);
        gateway_profiles_table::register_table(client_cache);
        gateway_sessions_table::register_table(client_cache);
        gateway_world_players_table::register_table(client_cache);
        my_gateway_table::register_table(client_cache);
        person_table::register_table(client_cache);
    }
    const ALL_TABLE_NAMES: &'static [&'static str] = &[
        "admin_lease_diagnostic",
        "admin_session_diagnostics",
        "gateway_block_actions",
        "gateway_chat_messages",
        "gateway_chunk_snapshots",
        "gateway_game_modes",
        "gateway_inventory_snapshots",
        "gateway_player_state",
        "gateway_profiles",
        "gateway_sessions",
        "gateway_world_players",
        "my_gateway",
        "person",
    ];
}
