// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::gateway_type::Gateway;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_gateway`.
///
/// Obtain a handle from the [`MyGatewayTableAccess::my_gateway`] method on [`super::RemoteTables`],
/// like `ctx.db.my_gateway()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_gateway().on_insert(...)`.
pub struct MyGatewayTableHandle<'ctx> {
    imp: __sdk::TableHandle<Gateway>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `my_gateway`.
pub struct MyGatewayTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for MyGatewayTableAccessor {
    type Row = Gateway;
    type Handle<'db> = MyGatewayTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.my_gateway()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_gateway`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyGatewayTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyGatewayTableHandle`], which mediates access to the table `my_gateway`.
    fn my_gateway(&self) -> MyGatewayTableHandle<'_>;
}

impl MyGatewayTableAccess for super::RemoteTables {
    fn my_gateway(&self) -> MyGatewayTableHandle<'_> {
        MyGatewayTableHandle {
            imp: self.imp.get_table::<Gateway>("my_gateway"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyGatewayInsertCallbackId(__sdk::CallbackId);
pub struct MyGatewayDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for MyGatewayTableHandle<'ctx> {
    type Row = Gateway;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Gateway> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for MyGatewayTableHandle<'ctx> {
    type Row = Gateway;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Gateway> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyGatewayInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyGatewayInsertCallbackId {
        MyGatewayInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyGatewayInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyGatewayDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyGatewayDeleteCallbackId {
        MyGatewayDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyGatewayDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for MyGatewayTableHandle<'ctx> {
    type InsertCallbackId = MyGatewayInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyGatewayInsertCallbackId {
        MyGatewayInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyGatewayInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for MyGatewayTableHandle<'ctx> {
    type DeleteCallbackId = MyGatewayDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyGatewayDeleteCallbackId {
        MyGatewayDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyGatewayDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct MyGatewayUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for MyGatewayTableHandle<'ctx> {
    type UpdateCallbackId = MyGatewayUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MyGatewayUpdateCallbackId {
        MyGatewayUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MyGatewayUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for MyGatewayTableHandle<'ctx> {
    type UpdateCallbackId = MyGatewayUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MyGatewayUpdateCallbackId {
        MyGatewayUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MyGatewayUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `identity` unique index on the table `my_gateway`,
/// which allows point queries on the field of the same name
/// via the [`MyGatewayIdentityUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_gateway().identity().find(...)`.
pub struct MyGatewayIdentityUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Gateway, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> MyGatewayTableHandle<'ctx> {
    /// Get a handle on the `identity` unique index on the table `my_gateway`.
    pub fn identity(&self) -> MyGatewayIdentityUnique<'ctx> {
        MyGatewayIdentityUnique {
            imp: self
                .imp
                .get_unique_constraint::<__sdk::Identity>("identity"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> MyGatewayIdentityUnique<'ctx> {
    /// Find the subscribed row whose `identity` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<Gateway> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Gateway>("my_gateway");
    _table.add_unique_constraint::<__sdk::Identity>("identity", |row| &row.identity);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Gateway>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Gateway>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Gateway`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_gatewayQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Gateway`.
    fn my_gateway(&self) -> __sdk::__query_builder::Table<Gateway>;
}

impl my_gatewayQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_gateway(&self) -> __sdk::__query_builder::Table<Gateway> {
        __sdk::__query_builder::Table::new("my_gateway")
    }
}
