// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::identity_kind_type::IdentityKind;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PlayerProfile {
    pub player_uuid: __sdk::Uuid,
    pub username: String,
    pub identity_kind: IdentityKind,
    pub first_seen: __sdk::Timestamp,
    pub last_seen: __sdk::Timestamp,
}

impl __sdk::InModule for PlayerProfile {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PlayerProfile`.
///
/// Provides typed access to columns for query building.
pub struct PlayerProfileCols {
    pub player_uuid: __sdk::__query_builder::Col<PlayerProfile, __sdk::Uuid>,
    pub username: __sdk::__query_builder::Col<PlayerProfile, String>,
    pub identity_kind: __sdk::__query_builder::Col<PlayerProfile, IdentityKind>,
    pub first_seen: __sdk::__query_builder::Col<PlayerProfile, __sdk::Timestamp>,
    pub last_seen: __sdk::__query_builder::Col<PlayerProfile, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for PlayerProfile {
    type Cols = PlayerProfileCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PlayerProfileCols {
            player_uuid: __sdk::__query_builder::Col::new(table_name, "player_uuid"),
            username: __sdk::__query_builder::Col::new(table_name, "username"),
            identity_kind: __sdk::__query_builder::Col::new(table_name, "identity_kind"),
            first_seen: __sdk::__query_builder::Col::new(table_name, "first_seen"),
            last_seen: __sdk::__query_builder::Col::new(table_name, "last_seen"),
        }
    }
}

/// Indexed column accessor struct for the table `PlayerProfile`.
///
/// Provides typed access to indexed columns for query building.
pub struct PlayerProfileIxCols {
    pub player_uuid: __sdk::__query_builder::IxCol<PlayerProfile, __sdk::Uuid>,
}

impl __sdk::__query_builder::HasIxCols for PlayerProfile {
    type IxCols = PlayerProfileIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PlayerProfileIxCols {
            player_uuid: __sdk::__query_builder::IxCol::new(table_name, "player_uuid"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PlayerProfile {}
