// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::session_phase_type::SessionPhase;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PlayerSession {
    pub session_uuid: __sdk::Uuid,
    pub player_uuid: __sdk::Uuid,
    pub gateway_identity: __sdk::Identity,
    pub owner_connection: __sdk::ConnectionId,
    pub phase: SessionPhase,
    pub connected_at: __sdk::Timestamp,
    pub last_activity: __sdk::Timestamp,
    pub entity_id: i32,
}

impl __sdk::InModule for PlayerSession {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PlayerSession`.
///
/// Provides typed access to columns for query building.
pub struct PlayerSessionCols {
    pub session_uuid: __sdk::__query_builder::Col<PlayerSession, __sdk::Uuid>,
    pub player_uuid: __sdk::__query_builder::Col<PlayerSession, __sdk::Uuid>,
    pub gateway_identity: __sdk::__query_builder::Col<PlayerSession, __sdk::Identity>,
    pub owner_connection: __sdk::__query_builder::Col<PlayerSession, __sdk::ConnectionId>,
    pub phase: __sdk::__query_builder::Col<PlayerSession, SessionPhase>,
    pub connected_at: __sdk::__query_builder::Col<PlayerSession, __sdk::Timestamp>,
    pub last_activity: __sdk::__query_builder::Col<PlayerSession, __sdk::Timestamp>,
    pub entity_id: __sdk::__query_builder::Col<PlayerSession, i32>,
}

impl __sdk::__query_builder::HasCols for PlayerSession {
    type Cols = PlayerSessionCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PlayerSessionCols {
            session_uuid: __sdk::__query_builder::Col::new(table_name, "session_uuid"),
            player_uuid: __sdk::__query_builder::Col::new(table_name, "player_uuid"),
            gateway_identity: __sdk::__query_builder::Col::new(table_name, "gateway_identity"),
            owner_connection: __sdk::__query_builder::Col::new(table_name, "owner_connection"),
            phase: __sdk::__query_builder::Col::new(table_name, "phase"),
            connected_at: __sdk::__query_builder::Col::new(table_name, "connected_at"),
            last_activity: __sdk::__query_builder::Col::new(table_name, "last_activity"),
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
        }
    }
}

/// Indexed column accessor struct for the table `PlayerSession`.
///
/// Provides typed access to indexed columns for query building.
pub struct PlayerSessionIxCols {
    pub gateway_identity: __sdk::__query_builder::IxCol<PlayerSession, __sdk::Identity>,
    pub last_activity: __sdk::__query_builder::IxCol<PlayerSession, __sdk::Timestamp>,
    pub player_uuid: __sdk::__query_builder::IxCol<PlayerSession, __sdk::Uuid>,
    pub session_uuid: __sdk::__query_builder::IxCol<PlayerSession, __sdk::Uuid>,
}

impl __sdk::__query_builder::HasIxCols for PlayerSession {
    type IxCols = PlayerSessionIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PlayerSessionIxCols {
            gateway_identity: __sdk::__query_builder::IxCol::new(table_name, "gateway_identity"),
            last_activity: __sdk::__query_builder::IxCol::new(table_name, "last_activity"),
            player_uuid: __sdk::__query_builder::IxCol::new(table_name, "player_uuid"),
            session_uuid: __sdk::__query_builder::IxCol::new(table_name, "session_uuid"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PlayerSession {}
