// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PlayerChatRate {
    pub session_uuid: __sdk::Uuid,
    pub window_started: __sdk::Timestamp,
    pub sent_count: u8,
}

impl __sdk::InModule for PlayerChatRate {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PlayerChatRate`.
///
/// Provides typed access to columns for query building.
pub struct PlayerChatRateCols {
    pub session_uuid: __sdk::__query_builder::Col<PlayerChatRate, __sdk::Uuid>,
    pub window_started: __sdk::__query_builder::Col<PlayerChatRate, __sdk::Timestamp>,
    pub sent_count: __sdk::__query_builder::Col<PlayerChatRate, u8>,
}

impl __sdk::__query_builder::HasCols for PlayerChatRate {
    type Cols = PlayerChatRateCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PlayerChatRateCols {
            session_uuid: __sdk::__query_builder::Col::new(table_name, "session_uuid"),
            window_started: __sdk::__query_builder::Col::new(table_name, "window_started"),
            sent_count: __sdk::__query_builder::Col::new(table_name, "sent_count"),
        }
    }
}

/// Indexed column accessor struct for the table `PlayerChatRate`.
///
/// Provides typed access to indexed columns for query building.
pub struct PlayerChatRateIxCols {
    pub session_uuid: __sdk::__query_builder::IxCol<PlayerChatRate, __sdk::Uuid>,
}

impl __sdk::__query_builder::HasIxCols for PlayerChatRate {
    type IxCols = PlayerChatRateIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PlayerChatRateIxCols {
            session_uuid: __sdk::__query_builder::IxCol::new(table_name, "session_uuid"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PlayerChatRate {}
