// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PlayerPose {
    pub session_uuid: __sdk::Uuid,
    pub x: f64,
    pub y: f64,
    pub z: f64,
    pub yaw: f32,
    pub pitch: f32,
    pub on_ground: bool,
    pub revision: u64,
}

impl __sdk::InModule for PlayerPose {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PlayerPose`.
///
/// Provides typed access to columns for query building.
pub struct PlayerPoseCols {
    pub session_uuid: __sdk::__query_builder::Col<PlayerPose, __sdk::Uuid>,
    pub x: __sdk::__query_builder::Col<PlayerPose, f64>,
    pub y: __sdk::__query_builder::Col<PlayerPose, f64>,
    pub z: __sdk::__query_builder::Col<PlayerPose, f64>,
    pub yaw: __sdk::__query_builder::Col<PlayerPose, f32>,
    pub pitch: __sdk::__query_builder::Col<PlayerPose, f32>,
    pub on_ground: __sdk::__query_builder::Col<PlayerPose, bool>,
    pub revision: __sdk::__query_builder::Col<PlayerPose, u64>,
}

impl __sdk::__query_builder::HasCols for PlayerPose {
    type Cols = PlayerPoseCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PlayerPoseCols {
            session_uuid: __sdk::__query_builder::Col::new(table_name, "session_uuid"),
            x: __sdk::__query_builder::Col::new(table_name, "x"),
            y: __sdk::__query_builder::Col::new(table_name, "y"),
            z: __sdk::__query_builder::Col::new(table_name, "z"),
            yaw: __sdk::__query_builder::Col::new(table_name, "yaw"),
            pitch: __sdk::__query_builder::Col::new(table_name, "pitch"),
            on_ground: __sdk::__query_builder::Col::new(table_name, "on_ground"),
            revision: __sdk::__query_builder::Col::new(table_name, "revision"),
        }
    }
}

/// Indexed column accessor struct for the table `PlayerPose`.
///
/// Provides typed access to indexed columns for query building.
pub struct PlayerPoseIxCols {
    pub session_uuid: __sdk::__query_builder::IxCol<PlayerPose, __sdk::Uuid>,
}

impl __sdk::__query_builder::HasIxCols for PlayerPose {
    type IxCols = PlayerPoseIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PlayerPoseIxCols {
            session_uuid: __sdk::__query_builder::IxCol::new(table_name, "session_uuid"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PlayerPose {}
