// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PlayerVitals {
    pub player_uuid: __sdk::Uuid,
    pub health: u8,
    pub food: u8,
    pub dead: bool,
    pub revision: u64,
    pub respawn_revision: Option<u64>,
    pub connected_gateway: Option<__sdk::Identity>,
    pub connected_session: Option<__sdk::Uuid>,
}

impl __sdk::InModule for PlayerVitals {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PlayerVitals`.
///
/// Provides typed access to columns for query building.
pub struct PlayerVitalsCols {
    pub player_uuid: __sdk::__query_builder::Col<PlayerVitals, __sdk::Uuid>,
    pub health: __sdk::__query_builder::Col<PlayerVitals, u8>,
    pub food: __sdk::__query_builder::Col<PlayerVitals, u8>,
    pub dead: __sdk::__query_builder::Col<PlayerVitals, bool>,
    pub revision: __sdk::__query_builder::Col<PlayerVitals, u64>,
    pub respawn_revision: __sdk::__query_builder::Col<PlayerVitals, Option<u64>>,
    pub connected_gateway: __sdk::__query_builder::Col<PlayerVitals, Option<__sdk::Identity>>,
    pub connected_session: __sdk::__query_builder::Col<PlayerVitals, Option<__sdk::Uuid>>,
}

impl __sdk::__query_builder::HasCols for PlayerVitals {
    type Cols = PlayerVitalsCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PlayerVitalsCols {
            player_uuid: __sdk::__query_builder::Col::new(table_name, "player_uuid"),
            health: __sdk::__query_builder::Col::new(table_name, "health"),
            food: __sdk::__query_builder::Col::new(table_name, "food"),
            dead: __sdk::__query_builder::Col::new(table_name, "dead"),
            revision: __sdk::__query_builder::Col::new(table_name, "revision"),
            respawn_revision: __sdk::__query_builder::Col::new(table_name, "respawn_revision"),
            connected_gateway: __sdk::__query_builder::Col::new(table_name, "connected_gateway"),
            connected_session: __sdk::__query_builder::Col::new(table_name, "connected_session"),
        }
    }
}

/// Indexed column accessor struct for the table `PlayerVitals`.
///
/// Provides typed access to indexed columns for query building.
pub struct PlayerVitalsIxCols {
    pub player_uuid: __sdk::__query_builder::IxCol<PlayerVitals, __sdk::Uuid>,
}

impl __sdk::__query_builder::HasIxCols for PlayerVitals {
    type IxCols = PlayerVitalsIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PlayerVitalsIxCols {
            player_uuid: __sdk::__query_builder::IxCol::new(table_name, "player_uuid"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PlayerVitals {}
