// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PlayerChatMessage {
    pub message_id: u64,
    pub gateway_identity: __sdk::Identity,
    pub gateway_sequence: u64,
    pub session_uuid: __sdk::Uuid,
    pub player_uuid: __sdk::Uuid,
    pub username: String,
    pub text: String,
    pub sent_at: __sdk::Timestamp,
}

impl __sdk::InModule for PlayerChatMessage {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PlayerChatMessage`.
///
/// Provides typed access to columns for query building.
pub struct PlayerChatMessageCols {
    pub message_id: __sdk::__query_builder::Col<PlayerChatMessage, u64>,
    pub gateway_identity: __sdk::__query_builder::Col<PlayerChatMessage, __sdk::Identity>,
    pub gateway_sequence: __sdk::__query_builder::Col<PlayerChatMessage, u64>,
    pub session_uuid: __sdk::__query_builder::Col<PlayerChatMessage, __sdk::Uuid>,
    pub player_uuid: __sdk::__query_builder::Col<PlayerChatMessage, __sdk::Uuid>,
    pub username: __sdk::__query_builder::Col<PlayerChatMessage, String>,
    pub text: __sdk::__query_builder::Col<PlayerChatMessage, String>,
    pub sent_at: __sdk::__query_builder::Col<PlayerChatMessage, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for PlayerChatMessage {
    type Cols = PlayerChatMessageCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PlayerChatMessageCols {
            message_id: __sdk::__query_builder::Col::new(table_name, "message_id"),
            gateway_identity: __sdk::__query_builder::Col::new(table_name, "gateway_identity"),
            gateway_sequence: __sdk::__query_builder::Col::new(table_name, "gateway_sequence"),
            session_uuid: __sdk::__query_builder::Col::new(table_name, "session_uuid"),
            player_uuid: __sdk::__query_builder::Col::new(table_name, "player_uuid"),
            username: __sdk::__query_builder::Col::new(table_name, "username"),
            text: __sdk::__query_builder::Col::new(table_name, "text"),
            sent_at: __sdk::__query_builder::Col::new(table_name, "sent_at"),
        }
    }
}

/// Indexed column accessor struct for the table `PlayerChatMessage`.
///
/// Provides typed access to indexed columns for query building.
pub struct PlayerChatMessageIxCols {
    pub gateway_identity: __sdk::__query_builder::IxCol<PlayerChatMessage, __sdk::Identity>,
    pub message_id: __sdk::__query_builder::IxCol<PlayerChatMessage, u64>,
}

impl __sdk::__query_builder::HasIxCols for PlayerChatMessage {
    type IxCols = PlayerChatMessageIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PlayerChatMessageIxCols {
            gateway_identity: __sdk::__query_builder::IxCol::new(table_name, "gateway_identity"),
            message_id: __sdk::__query_builder::IxCol::new(table_name, "message_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PlayerChatMessage {}
