// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::game_mode_type::GameMode;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PlayerGameMode {
    pub player_uuid: __sdk::Uuid,
    pub mode: GameMode,
}

impl __sdk::InModule for PlayerGameMode {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PlayerGameMode`.
///
/// Provides typed access to columns for query building.
pub struct PlayerGameModeCols {
    pub player_uuid: __sdk::__query_builder::Col<PlayerGameMode, __sdk::Uuid>,
    pub mode: __sdk::__query_builder::Col<PlayerGameMode, GameMode>,
}

impl __sdk::__query_builder::HasCols for PlayerGameMode {
    type Cols = PlayerGameModeCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PlayerGameModeCols {
            player_uuid: __sdk::__query_builder::Col::new(table_name, "player_uuid"),
            mode: __sdk::__query_builder::Col::new(table_name, "mode"),
        }
    }
}

/// Indexed column accessor struct for the table `PlayerGameMode`.
///
/// Provides typed access to indexed columns for query building.
pub struct PlayerGameModeIxCols {
    pub player_uuid: __sdk::__query_builder::IxCol<PlayerGameMode, __sdk::Uuid>,
}

impl __sdk::__query_builder::HasIxCols for PlayerGameMode {
    type IxCols = PlayerGameModeIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PlayerGameModeIxCols {
            player_uuid: __sdk::__query_builder::IxCol::new(table_name, "player_uuid"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PlayerGameMode {}
