// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PlayerInventory {
    pub player_uuid: __sdk::Uuid,
    pub slots: Vec<u8>,
    pub cursor: Vec<u8>,
    pub selected: u8,
    pub revision: i32,
    pub drag_kind: i8,
    pub drag_slots: Vec<u8>,
}

impl __sdk::InModule for PlayerInventory {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PlayerInventory`.
///
/// Provides typed access to columns for query building.
pub struct PlayerInventoryCols {
    pub player_uuid: __sdk::__query_builder::Col<PlayerInventory, __sdk::Uuid>,
    pub slots: __sdk::__query_builder::Col<PlayerInventory, Vec<u8>>,
    pub cursor: __sdk::__query_builder::Col<PlayerInventory, Vec<u8>>,
    pub selected: __sdk::__query_builder::Col<PlayerInventory, u8>,
    pub revision: __sdk::__query_builder::Col<PlayerInventory, i32>,
    pub drag_kind: __sdk::__query_builder::Col<PlayerInventory, i8>,
    pub drag_slots: __sdk::__query_builder::Col<PlayerInventory, Vec<u8>>,
}

impl __sdk::__query_builder::HasCols for PlayerInventory {
    type Cols = PlayerInventoryCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PlayerInventoryCols {
            player_uuid: __sdk::__query_builder::Col::new(table_name, "player_uuid"),
            slots: __sdk::__query_builder::Col::new(table_name, "slots"),
            cursor: __sdk::__query_builder::Col::new(table_name, "cursor"),
            selected: __sdk::__query_builder::Col::new(table_name, "selected"),
            revision: __sdk::__query_builder::Col::new(table_name, "revision"),
            drag_kind: __sdk::__query_builder::Col::new(table_name, "drag_kind"),
            drag_slots: __sdk::__query_builder::Col::new(table_name, "drag_slots"),
        }
    }
}

/// Indexed column accessor struct for the table `PlayerInventory`.
///
/// Provides typed access to indexed columns for query building.
pub struct PlayerInventoryIxCols {
    pub player_uuid: __sdk::__query_builder::IxCol<PlayerInventory, __sdk::Uuid>,
}

impl __sdk::__query_builder::HasIxCols for PlayerInventory {
    type IxCols = PlayerInventoryIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PlayerInventoryIxCols {
            player_uuid: __sdk::__query_builder::IxCol::new(table_name, "player_uuid"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PlayerInventory {}
