// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RegisterGatewayArgs {
    pub identity: __sdk::Identity,
}

impl From<RegisterGatewayArgs> for super::Reducer {
    fn from(args: RegisterGatewayArgs) -> Self {
        Self::RegisterGateway {
            identity: args.identity,
        }
    }
}

impl __sdk::InModule for RegisterGatewayArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `register_gateway`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait register_gateway {
    /// Request that the remote module invoke the reducer `register_gateway` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`register_gateway:register_gateway_then`] to run a callback after the reducer completes.
    fn register_gateway(&self, identity: __sdk::Identity) -> __sdk::Result<()> {
        self.register_gateway_then(identity, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `register_gateway` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn register_gateway_then(
        &self,
        identity: __sdk::Identity,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl register_gateway for super::RemoteReducers {
    fn register_gateway_then(
        &self,
        identity: __sdk::Identity,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(RegisterGatewayArgs { identity }, callback)
    }
}
