// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RequestPlayerRespawnArgs {
    pub session_uuid: __sdk::Uuid,
}

impl From<RequestPlayerRespawnArgs> for super::Reducer {
    fn from(args: RequestPlayerRespawnArgs) -> Self {
        Self::RequestPlayerRespawn {
            session_uuid: args.session_uuid,
        }
    }
}

impl __sdk::InModule for RequestPlayerRespawnArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `request_player_respawn`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait request_player_respawn {
    /// Request that the remote module invoke the reducer `request_player_respawn` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`request_player_respawn:request_player_respawn_then`] to run a callback after the reducer completes.
    fn request_player_respawn(&self, session_uuid: __sdk::Uuid) -> __sdk::Result<()> {
        self.request_player_respawn_then(session_uuid, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `request_player_respawn` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn request_player_respawn_then(
        &self,
        session_uuid: __sdk::Uuid,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl request_player_respawn for super::RemoteReducers {
    fn request_player_respawn_then(
        &self,
        session_uuid: __sdk::Uuid,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(RequestPlayerRespawnArgs { session_uuid }, callback)
    }
}
