// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SessionLeaseMetrics {
    pub key: u8,
    pub expired_total: u64,
    pub last_expired_at: Option<__sdk::Timestamp>,
    pub observed_at: __sdk::Timestamp,
}

impl __sdk::InModule for SessionLeaseMetrics {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SessionLeaseMetrics`.
///
/// Provides typed access to columns for query building.
pub struct SessionLeaseMetricsCols {
    pub key: __sdk::__query_builder::Col<SessionLeaseMetrics, u8>,
    pub expired_total: __sdk::__query_builder::Col<SessionLeaseMetrics, u64>,
    pub last_expired_at: __sdk::__query_builder::Col<SessionLeaseMetrics, Option<__sdk::Timestamp>>,
    pub observed_at: __sdk::__query_builder::Col<SessionLeaseMetrics, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for SessionLeaseMetrics {
    type Cols = SessionLeaseMetricsCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SessionLeaseMetricsCols {
            key: __sdk::__query_builder::Col::new(table_name, "key"),
            expired_total: __sdk::__query_builder::Col::new(table_name, "expired_total"),
            last_expired_at: __sdk::__query_builder::Col::new(table_name, "last_expired_at"),
            observed_at: __sdk::__query_builder::Col::new(table_name, "observed_at"),
        }
    }
}

/// Indexed column accessor struct for the table `SessionLeaseMetrics`.
///
/// Provides typed access to indexed columns for query building.
pub struct SessionLeaseMetricsIxCols {
    pub key: __sdk::__query_builder::IxCol<SessionLeaseMetrics, u8>,
}

impl __sdk::__query_builder::HasIxCols for SessionLeaseMetrics {
    type IxCols = SessionLeaseMetricsIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SessionLeaseMetricsIxCols {
            key: __sdk::__query_builder::IxCol::new(table_name, "key"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SessionLeaseMetrics {}
