// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SessionEntity {
    pub id: u64,
    pub session_uuid: __sdk::Uuid,
}

impl __sdk::InModule for SessionEntity {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SessionEntity`.
///
/// Provides typed access to columns for query building.
pub struct SessionEntityCols {
    pub id: __sdk::__query_builder::Col<SessionEntity, u64>,
    pub session_uuid: __sdk::__query_builder::Col<SessionEntity, __sdk::Uuid>,
}

impl __sdk::__query_builder::HasCols for SessionEntity {
    type Cols = SessionEntityCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SessionEntityCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            session_uuid: __sdk::__query_builder::Col::new(table_name, "session_uuid"),
        }
    }
}

/// Indexed column accessor struct for the table `SessionEntity`.
///
/// Provides typed access to indexed columns for query building.
pub struct SessionEntityIxCols {
    pub id: __sdk::__query_builder::IxCol<SessionEntity, u64>,
    pub session_uuid: __sdk::__query_builder::IxCol<SessionEntity, __sdk::Uuid>,
}

impl __sdk::__query_builder::HasIxCols for SessionEntity {
    type IxCols = SessionEntityIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SessionEntityIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            session_uuid: __sdk::__query_builder::IxCol::new(table_name, "session_uuid"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SessionEntity {}
