// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SessionLeaseCleanup {
    pub scheduled_id: u64,
    pub scheduled_at: __sdk::ScheduleAt,
}

impl __sdk::InModule for SessionLeaseCleanup {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SessionLeaseCleanup`.
///
/// Provides typed access to columns for query building.
pub struct SessionLeaseCleanupCols {
    pub scheduled_id: __sdk::__query_builder::Col<SessionLeaseCleanup, u64>,
    pub scheduled_at: __sdk::__query_builder::Col<SessionLeaseCleanup, __sdk::ScheduleAt>,
}

impl __sdk::__query_builder::HasCols for SessionLeaseCleanup {
    type Cols = SessionLeaseCleanupCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SessionLeaseCleanupCols {
            scheduled_id: __sdk::__query_builder::Col::new(table_name, "scheduled_id"),
            scheduled_at: __sdk::__query_builder::Col::new(table_name, "scheduled_at"),
        }
    }
}

/// Indexed column accessor struct for the table `SessionLeaseCleanup`.
///
/// Provides typed access to indexed columns for query building.
pub struct SessionLeaseCleanupIxCols {
    pub scheduled_id: __sdk::__query_builder::IxCol<SessionLeaseCleanup, u64>,
}

impl __sdk::__query_builder::HasIxCols for SessionLeaseCleanup {
    type IxCols = SessionLeaseCleanupIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SessionLeaseCleanupIxCols {
            scheduled_id: __sdk::__query_builder::IxCol::new(table_name, "scheduled_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SessionLeaseCleanup {}
