// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::gateway_chat_mode_type::GatewayChatMode;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetGatewayChatModeArgs {
    pub gateway_identity: __sdk::Identity,
    pub mode: GatewayChatMode,
}

impl From<SetGatewayChatModeArgs> for super::Reducer {
    fn from(args: SetGatewayChatModeArgs) -> Self {
        Self::SetGatewayChatMode {
            gateway_identity: args.gateway_identity,
            mode: args.mode,
        }
    }
}

impl __sdk::InModule for SetGatewayChatModeArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_gateway_chat_mode`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_gateway_chat_mode {
    /// Request that the remote module invoke the reducer `set_gateway_chat_mode` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_gateway_chat_mode:set_gateway_chat_mode_then`] to run a callback after the reducer completes.
    fn set_gateway_chat_mode(
        &self,
        gateway_identity: __sdk::Identity,
        mode: GatewayChatMode,
    ) -> __sdk::Result<()> {
        self.set_gateway_chat_mode_then(gateway_identity, mode, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_gateway_chat_mode` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_gateway_chat_mode_then(
        &self,
        gateway_identity: __sdk::Identity,
        mode: GatewayChatMode,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_gateway_chat_mode for super::RemoteReducers {
    fn set_gateway_chat_mode_then(
        &self,
        gateway_identity: __sdk::Identity,
        mode: GatewayChatMode,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SetGatewayChatModeArgs {
                gateway_identity,
                mode,
            },
            callback,
        )
    }
}
