// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SimpleStorage {
    pub storage_uuid: __sdk::Uuid,
    pub title: String,
    pub slots: Vec<u8>,
    pub revision: i32,
}

impl __sdk::InModule for SimpleStorage {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SimpleStorage`.
///
/// Provides typed access to columns for query building.
pub struct SimpleStorageCols {
    pub storage_uuid: __sdk::__query_builder::Col<SimpleStorage, __sdk::Uuid>,
    pub title: __sdk::__query_builder::Col<SimpleStorage, String>,
    pub slots: __sdk::__query_builder::Col<SimpleStorage, Vec<u8>>,
    pub revision: __sdk::__query_builder::Col<SimpleStorage, i32>,
}

impl __sdk::__query_builder::HasCols for SimpleStorage {
    type Cols = SimpleStorageCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SimpleStorageCols {
            storage_uuid: __sdk::__query_builder::Col::new(table_name, "storage_uuid"),
            title: __sdk::__query_builder::Col::new(table_name, "title"),
            slots: __sdk::__query_builder::Col::new(table_name, "slots"),
            revision: __sdk::__query_builder::Col::new(table_name, "revision"),
        }
    }
}

/// Indexed column accessor struct for the table `SimpleStorage`.
///
/// Provides typed access to indexed columns for query building.
pub struct SimpleStorageIxCols {
    pub storage_uuid: __sdk::__query_builder::IxCol<SimpleStorage, __sdk::Uuid>,
}

impl __sdk::__query_builder::HasIxCols for SimpleStorage {
    type IxCols = SimpleStorageIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SimpleStorageIxCols {
            storage_uuid: __sdk::__query_builder::IxCol::new(table_name, "storage_uuid"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SimpleStorage {}
