// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct StorageAccess {
    pub key: String,
    pub player_uuid: __sdk::Uuid,
    pub storage_uuid: __sdk::Uuid,
}

impl __sdk::InModule for StorageAccess {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `StorageAccess`.
///
/// Provides typed access to columns for query building.
pub struct StorageAccessCols {
    pub key: __sdk::__query_builder::Col<StorageAccess, String>,
    pub player_uuid: __sdk::__query_builder::Col<StorageAccess, __sdk::Uuid>,
    pub storage_uuid: __sdk::__query_builder::Col<StorageAccess, __sdk::Uuid>,
}

impl __sdk::__query_builder::HasCols for StorageAccess {
    type Cols = StorageAccessCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        StorageAccessCols {
            key: __sdk::__query_builder::Col::new(table_name, "key"),
            player_uuid: __sdk::__query_builder::Col::new(table_name, "player_uuid"),
            storage_uuid: __sdk::__query_builder::Col::new(table_name, "storage_uuid"),
        }
    }
}

/// Indexed column accessor struct for the table `StorageAccess`.
///
/// Provides typed access to indexed columns for query building.
pub struct StorageAccessIxCols {
    pub key: __sdk::__query_builder::IxCol<StorageAccess, String>,
    pub player_uuid: __sdk::__query_builder::IxCol<StorageAccess, __sdk::Uuid>,
}

impl __sdk::__query_builder::HasIxCols for StorageAccess {
    type IxCols = StorageAccessIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        StorageAccessIxCols {
            key: __sdk::__query_builder::IxCol::new(table_name, "key"),
            player_uuid: __sdk::__query_builder::IxCol::new(table_name, "player_uuid"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for StorageAccess {}
