// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdatePlayerVitalsArgs {
    pub session_uuid: __sdk::Uuid,
    pub health: u8,
    pub food: u8,
    pub dead: bool,
    pub expected_revision: u64,
}

impl From<UpdatePlayerVitalsArgs> for super::Reducer {
    fn from(args: UpdatePlayerVitalsArgs) -> Self {
        Self::UpdatePlayerVitals {
            session_uuid: args.session_uuid,
            health: args.health,
            food: args.food,
            dead: args.dead,
            expected_revision: args.expected_revision,
        }
    }
}

impl __sdk::InModule for UpdatePlayerVitalsArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_player_vitals`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_player_vitals {
    /// Request that the remote module invoke the reducer `update_player_vitals` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_player_vitals:update_player_vitals_then`] to run a callback after the reducer completes.
    fn update_player_vitals(
        &self,
        session_uuid: __sdk::Uuid,
        health: u8,
        food: u8,
        dead: bool,
        expected_revision: u64,
    ) -> __sdk::Result<()> {
        self.update_player_vitals_then(
            session_uuid,
            health,
            food,
            dead,
            expected_revision,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `update_player_vitals` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_player_vitals_then(
        &self,
        session_uuid: __sdk::Uuid,
        health: u8,
        food: u8,
        dead: bool,
        expected_revision: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_player_vitals for super::RemoteReducers {
    fn update_player_vitals_then(
        &self,
        session_uuid: __sdk::Uuid,
        health: u8,
        food: u8,
        dead: bool,
        expected_revision: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UpdatePlayerVitalsArgs {
                session_uuid,
                health,
                food,
                dead,
                expected_revision,
            },
            callback,
        )
    }
}
