// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::player_pose_update_type::PlayerPoseUpdate;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdatePlayerStatesArgs {
    pub updates: Vec<PlayerPoseUpdate>,
}

impl From<UpdatePlayerStatesArgs> for super::Reducer {
    fn from(args: UpdatePlayerStatesArgs) -> Self {
        Self::UpdatePlayerStates {
            updates: args.updates,
        }
    }
}

impl __sdk::InModule for UpdatePlayerStatesArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_player_states`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_player_states {
    /// Request that the remote module invoke the reducer `update_player_states` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_player_states:update_player_states_then`] to run a callback after the reducer completes.
    fn update_player_states(&self, updates: Vec<PlayerPoseUpdate>) -> __sdk::Result<()> {
        self.update_player_states_then(updates, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `update_player_states` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_player_states_then(
        &self,
        updates: Vec<PlayerPoseUpdate>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_player_states for super::RemoteReducers {
    fn update_player_states_then(
        &self,
        updates: Vec<PlayerPoseUpdate>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(UpdatePlayerStatesArgs { updates }, callback)
    }
}
