// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateWorldInterestArgs {
    pub session_uuid: __sdk::Uuid,
    pub chunk_x: i32,
    pub chunk_z: i32,
    pub radius: u8,
}

impl From<UpdateWorldInterestArgs> for super::Reducer {
    fn from(args: UpdateWorldInterestArgs) -> Self {
        Self::UpdateWorldInterest {
            session_uuid: args.session_uuid,
            chunk_x: args.chunk_x,
            chunk_z: args.chunk_z,
            radius: args.radius,
        }
    }
}

impl __sdk::InModule for UpdateWorldInterestArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_world_interest`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_world_interest {
    /// Request that the remote module invoke the reducer `update_world_interest` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_world_interest:update_world_interest_then`] to run a callback after the reducer completes.
    fn update_world_interest(
        &self,
        session_uuid: __sdk::Uuid,
        chunk_x: i32,
        chunk_z: i32,
        radius: u8,
    ) -> __sdk::Result<()> {
        self.update_world_interest_then(session_uuid, chunk_x, chunk_z, radius, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `update_world_interest` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_world_interest_then(
        &self,
        session_uuid: __sdk::Uuid,
        chunk_x: i32,
        chunk_z: i32,
        radius: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_world_interest for super::RemoteReducers {
    fn update_world_interest_then(
        &self,
        session_uuid: __sdk::Uuid,
        chunk_x: i32,
        chunk_z: i32,
        radius: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UpdateWorldInterestArgs {
                session_uuid,
                chunk_x,
                chunk_z,
                radius,
            },
            callback,
        )
    }
}
