// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct WorldInterest {
    pub interest_key: String,
    pub session_uuid: __sdk::Uuid,
    pub gateway_identity: __sdk::Identity,
    pub world_id: String,
    pub chunk_key: String,
    pub chunk_x: i32,
    pub chunk_z: i32,
}

impl __sdk::InModule for WorldInterest {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `WorldInterest`.
///
/// Provides typed access to columns for query building.
pub struct WorldInterestCols {
    pub interest_key: __sdk::__query_builder::Col<WorldInterest, String>,
    pub session_uuid: __sdk::__query_builder::Col<WorldInterest, __sdk::Uuid>,
    pub gateway_identity: __sdk::__query_builder::Col<WorldInterest, __sdk::Identity>,
    pub world_id: __sdk::__query_builder::Col<WorldInterest, String>,
    pub chunk_key: __sdk::__query_builder::Col<WorldInterest, String>,
    pub chunk_x: __sdk::__query_builder::Col<WorldInterest, i32>,
    pub chunk_z: __sdk::__query_builder::Col<WorldInterest, i32>,
}

impl __sdk::__query_builder::HasCols for WorldInterest {
    type Cols = WorldInterestCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        WorldInterestCols {
            interest_key: __sdk::__query_builder::Col::new(table_name, "interest_key"),
            session_uuid: __sdk::__query_builder::Col::new(table_name, "session_uuid"),
            gateway_identity: __sdk::__query_builder::Col::new(table_name, "gateway_identity"),
            world_id: __sdk::__query_builder::Col::new(table_name, "world_id"),
            chunk_key: __sdk::__query_builder::Col::new(table_name, "chunk_key"),
            chunk_x: __sdk::__query_builder::Col::new(table_name, "chunk_x"),
            chunk_z: __sdk::__query_builder::Col::new(table_name, "chunk_z"),
        }
    }
}

/// Indexed column accessor struct for the table `WorldInterest`.
///
/// Provides typed access to indexed columns for query building.
pub struct WorldInterestIxCols {
    pub chunk_key: __sdk::__query_builder::IxCol<WorldInterest, String>,
    pub gateway_identity: __sdk::__query_builder::IxCol<WorldInterest, __sdk::Identity>,
    pub interest_key: __sdk::__query_builder::IxCol<WorldInterest, String>,
    pub session_uuid: __sdk::__query_builder::IxCol<WorldInterest, __sdk::Uuid>,
}

impl __sdk::__query_builder::HasIxCols for WorldInterest {
    type IxCols = WorldInterestIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        WorldInterestIxCols {
            chunk_key: __sdk::__query_builder::IxCol::new(table_name, "chunk_key"),
            gateway_identity: __sdk::__query_builder::IxCol::new(table_name, "gateway_identity"),
            interest_key: __sdk::__query_builder::IxCol::new(table_name, "interest_key"),
            session_uuid: __sdk::__query_builder::IxCol::new(table_name, "session_uuid"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for WorldInterest {}
