//! State/direction-scoped packet inventory for Java 26.3 / protocol 777.
//! Metadata is not a claim of codec implementation or runtime support.

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum State {
    Handshaking,
    Status,
    Login,
    Configuration,
    Play,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum Direction {
    Clientbound,
    Serverbound,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct PacketDescriptor {
    pub state: State,
    pub direction: Direction,
    pub id: i32,
    pub official_name: &'static str,
}
pub const PROTOCOL_VERSION: i32 = 777;
pub const SOURCE: &str = "https://minecraft.wiki/w/Java_Edition_protocol/Packets?oldid=3810839";
pub mod configuration;
pub mod handshaking;
pub mod login;
pub mod play;
pub mod status;
pub const PACKETS: &[PacketDescriptor] = &[
    handshaking::serverbound::intention::DESCRIPTOR,
    status::clientbound::status_response::DESCRIPTOR,
    status::clientbound::pong_response::DESCRIPTOR,
    status::serverbound::status_request::DESCRIPTOR,
    status::serverbound::ping_request::DESCRIPTOR,
    login::clientbound::login_disconnect::DESCRIPTOR,
    login::clientbound::hello::DESCRIPTOR,
    login::clientbound::login_finished::DESCRIPTOR,
    login::clientbound::login_compression::DESCRIPTOR,
    login::clientbound::custom_query::DESCRIPTOR,
    login::clientbound::cookie_request::DESCRIPTOR,
    login::serverbound::hello::DESCRIPTOR,
    login::serverbound::key::DESCRIPTOR,
    login::serverbound::custom_query_answer::DESCRIPTOR,
    login::serverbound::login_acknowledged::DESCRIPTOR,
    login::serverbound::cookie_response::DESCRIPTOR,
    configuration::clientbound::cookie_request::DESCRIPTOR,
    configuration::clientbound::custom_payload::DESCRIPTOR,
    configuration::clientbound::disconnect::DESCRIPTOR,
    configuration::clientbound::finish_configuration::DESCRIPTOR,
    configuration::clientbound::keep_alive::DESCRIPTOR,
    configuration::clientbound::ping::DESCRIPTOR,
    configuration::clientbound::reset_chat::DESCRIPTOR,
    configuration::clientbound::registry_data::DESCRIPTOR,
    configuration::clientbound::resource_pack_pop::DESCRIPTOR,
    configuration::clientbound::resource_pack_push::DESCRIPTOR,
    configuration::clientbound::post_effects::DESCRIPTOR,
    configuration::clientbound::store_cookie::DESCRIPTOR,
    configuration::clientbound::transfer::DESCRIPTOR,
    configuration::clientbound::update_enabled_features::DESCRIPTOR,
    configuration::clientbound::update_tags::DESCRIPTOR,
    configuration::clientbound::select_known_packs::DESCRIPTOR,
    configuration::clientbound::custom_report_details::DESCRIPTOR,
    configuration::clientbound::server_links::DESCRIPTOR,
    configuration::clientbound::clear_dialog::DESCRIPTOR,
    configuration::clientbound::show_dialog::DESCRIPTOR,
    configuration::clientbound::code_of_conduct::DESCRIPTOR,
    configuration::serverbound::client_information::DESCRIPTOR,
    configuration::serverbound::cookie_response::DESCRIPTOR,
    configuration::serverbound::custom_payload::DESCRIPTOR,
    configuration::serverbound::finish_configuration::DESCRIPTOR,
    configuration::serverbound::keep_alive::DESCRIPTOR,
    configuration::serverbound::pong::DESCRIPTOR,
    configuration::serverbound::resource_pack::DESCRIPTOR,
    configuration::serverbound::select_known_packs::DESCRIPTOR,
    configuration::serverbound::custom_click_action::DESCRIPTOR,
    configuration::serverbound::accept_code_of_conduct::DESCRIPTOR,
    play::clientbound::bundle_delimiter::DESCRIPTOR,
    play::clientbound::add_entity::DESCRIPTOR,
    play::clientbound::animate::DESCRIPTOR,
    play::clientbound::award_stats::DESCRIPTOR,
    play::clientbound::block_changed_ack::DESCRIPTOR,
    play::clientbound::block_destruction::DESCRIPTOR,
    play::clientbound::block_entity_data::DESCRIPTOR,
    play::clientbound::block_event::DESCRIPTOR,
    play::clientbound::block_update::DESCRIPTOR,
    play::clientbound::boss_event::DESCRIPTOR,
    play::clientbound::change_difficulty::DESCRIPTOR,
    play::clientbound::chunk_batch_finished::DESCRIPTOR,
    play::clientbound::chunk_batch_start::DESCRIPTOR,
    play::clientbound::chunks_biomes::DESCRIPTOR,
    play::clientbound::clear_titles::DESCRIPTOR,
    play::clientbound::command_suggestions::DESCRIPTOR,
    play::clientbound::commands::DESCRIPTOR,
    play::clientbound::container_close::DESCRIPTOR,
    play::clientbound::container_set_content::DESCRIPTOR,
    play::clientbound::container_set_data::DESCRIPTOR,
    play::clientbound::container_set_slot::DESCRIPTOR,
    play::clientbound::cookie_request::DESCRIPTOR,
    play::clientbound::cooldown::DESCRIPTOR,
    play::clientbound::custom_chat_completions::DESCRIPTOR,
    play::clientbound::custom_payload::DESCRIPTOR,
    play::clientbound::damage_event::DESCRIPTOR,
    play::clientbound::debug_block_value::DESCRIPTOR,
    play::clientbound::debug_chunk_value::DESCRIPTOR,
    play::clientbound::debug_entity_value::DESCRIPTOR,
    play::clientbound::debug_event::DESCRIPTOR,
    play::clientbound::debug_sample::DESCRIPTOR,
    play::clientbound::delete_chat::DESCRIPTOR,
    play::clientbound::disconnect::DESCRIPTOR,
    play::clientbound::disguised_chat::DESCRIPTOR,
    play::clientbound::entity_event::DESCRIPTOR,
    play::clientbound::entity_position_sync::DESCRIPTOR,
    play::clientbound::explode::DESCRIPTOR,
    play::clientbound::add_transient_block::DESCRIPTOR,
    play::clientbound::forget_level_chunk::DESCRIPTOR,
    play::clientbound::game_event::DESCRIPTOR,
    play::clientbound::game_rule_values::DESCRIPTOR,
    play::clientbound::game_test_highlight_pos::DESCRIPTOR,
    play::clientbound::mount_screen_open::DESCRIPTOR,
    play::clientbound::hurt_animation::DESCRIPTOR,
    play::clientbound::initialize_border::DESCRIPTOR,
    play::clientbound::keep_alive::DESCRIPTOR,
    play::clientbound::level_chunk_with_light::DESCRIPTOR,
    play::clientbound::level_event::DESCRIPTOR,
    play::clientbound::level_particles::DESCRIPTOR,
    play::clientbound::light_update::DESCRIPTOR,
    play::clientbound::login::DESCRIPTOR,
    play::clientbound::low_disk_space_warning::DESCRIPTOR,
    play::clientbound::map_item_data::DESCRIPTOR,
    play::clientbound::merchant_offers::DESCRIPTOR,
    play::clientbound::move_entity_pos::DESCRIPTOR,
    play::clientbound::move_entity_pos_rot::DESCRIPTOR,
    play::clientbound::move_minecart_along_track::DESCRIPTOR,
    play::clientbound::move_entity_rot::DESCRIPTOR,
    play::clientbound::move_vehicle::DESCRIPTOR,
    play::clientbound::open_book::DESCRIPTOR,
    play::clientbound::open_screen::DESCRIPTOR,
    play::clientbound::open_sign_editor::DESCRIPTOR,
    play::clientbound::ping::DESCRIPTOR,
    play::clientbound::pong_response::DESCRIPTOR,
    play::clientbound::place_ghost_recipe::DESCRIPTOR,
    play::clientbound::player_abilities::DESCRIPTOR,
    play::clientbound::player_chat::DESCRIPTOR,
    play::clientbound::player_combat_end::DESCRIPTOR,
    play::clientbound::player_combat_enter::DESCRIPTOR,
    play::clientbound::player_combat_kill::DESCRIPTOR,
    play::clientbound::player_info_remove::DESCRIPTOR,
    play::clientbound::player_info_update::DESCRIPTOR,
    play::clientbound::player_look_at::DESCRIPTOR,
    play::clientbound::player_position::DESCRIPTOR,
    play::clientbound::player_rotation::DESCRIPTOR,
    play::clientbound::recipe_book_add::DESCRIPTOR,
    play::clientbound::recipe_book_remove::DESCRIPTOR,
    play::clientbound::recipe_book_settings::DESCRIPTOR,
    play::clientbound::remove_entities::DESCRIPTOR,
    play::clientbound::remove_mob_effect::DESCRIPTOR,
    play::clientbound::reset_score::DESCRIPTOR,
    play::clientbound::resource_pack_pop::DESCRIPTOR,
    play::clientbound::resource_pack_push::DESCRIPTOR,
    play::clientbound::post_effects::DESCRIPTOR,
    play::clientbound::respawn::DESCRIPTOR,
    play::clientbound::rotate_head::DESCRIPTOR,
    play::clientbound::section_blocks_update::DESCRIPTOR,
    play::clientbound::select_advancements_tab::DESCRIPTOR,
    play::clientbound::server_data::DESCRIPTOR,
    play::clientbound::set_action_bar_text::DESCRIPTOR,
    play::clientbound::set_border_center::DESCRIPTOR,
    play::clientbound::set_border_lerp_size::DESCRIPTOR,
    play::clientbound::set_border_size::DESCRIPTOR,
    play::clientbound::set_border_warning_delay::DESCRIPTOR,
    play::clientbound::set_border_warning_distance::DESCRIPTOR,
    play::clientbound::set_camera::DESCRIPTOR,
    play::clientbound::set_chunk_cache_center::DESCRIPTOR,
    play::clientbound::set_chunk_cache_radius::DESCRIPTOR,
    play::clientbound::set_cursor_item::DESCRIPTOR,
    play::clientbound::set_default_spawn_position::DESCRIPTOR,
    play::clientbound::set_display_objective::DESCRIPTOR,
    play::clientbound::set_entity_data::DESCRIPTOR,
    play::clientbound::set_entity_link::DESCRIPTOR,
    play::clientbound::set_entity_motion::DESCRIPTOR,
    play::clientbound::set_equipment::DESCRIPTOR,
    play::clientbound::set_experience::DESCRIPTOR,
    play::clientbound::set_health::DESCRIPTOR,
    play::clientbound::set_held_slot::DESCRIPTOR,
    play::clientbound::set_objective::DESCRIPTOR,
    play::clientbound::set_passengers::DESCRIPTOR,
    play::clientbound::set_player_inventory::DESCRIPTOR,
    play::clientbound::set_player_team::DESCRIPTOR,
    play::clientbound::set_score::DESCRIPTOR,
    play::clientbound::set_simulation_distance::DESCRIPTOR,
    play::clientbound::set_subtitle_text::DESCRIPTOR,
    play::clientbound::set_time::DESCRIPTOR,
    play::clientbound::set_title_text::DESCRIPTOR,
    play::clientbound::set_titles_animation::DESCRIPTOR,
    play::clientbound::sound_entity::DESCRIPTOR,
    play::clientbound::sound::DESCRIPTOR,
    play::clientbound::start_configuration::DESCRIPTOR,
    play::clientbound::stop_sound::DESCRIPTOR,
    play::clientbound::store_cookie::DESCRIPTOR,
    play::clientbound::swing_animation::DESCRIPTOR,
    play::clientbound::system_chat::DESCRIPTOR,
    play::clientbound::tab_list::DESCRIPTOR,
    play::clientbound::tag_query::DESCRIPTOR,
    play::clientbound::take_item_entity::DESCRIPTOR,
    play::clientbound::teleport_entity::DESCRIPTOR,
    play::clientbound::test_instance_block_status::DESCRIPTOR,
    play::clientbound::ticking_state::DESCRIPTOR,
    play::clientbound::ticking_step::DESCRIPTOR,
    play::clientbound::transfer::DESCRIPTOR,
    play::clientbound::update_advancements::DESCRIPTOR,
    play::clientbound::update_attributes::DESCRIPTOR,
    play::clientbound::update_mob_effect::DESCRIPTOR,
    play::clientbound::update_recipes::DESCRIPTOR,
    play::clientbound::update_tags::DESCRIPTOR,
    play::clientbound::projectile_power::DESCRIPTOR,
    play::clientbound::custom_report_details::DESCRIPTOR,
    play::clientbound::server_links::DESCRIPTOR,
    play::clientbound::waypoint::DESCRIPTOR,
    play::clientbound::clear_dialog::DESCRIPTOR,
    play::clientbound::show_dialog::DESCRIPTOR,
    play::serverbound::accept_teleportation::DESCRIPTOR,
    play::serverbound::attack::DESCRIPTOR,
    play::serverbound::block_entity_tag_query::DESCRIPTOR,
    play::serverbound::bundle_item_selected::DESCRIPTOR,
    play::serverbound::change_difficulty::DESCRIPTOR,
    play::serverbound::change_game_mode::DESCRIPTOR,
    play::serverbound::chat_ack::DESCRIPTOR,
    play::serverbound::chat_command::DESCRIPTOR,
    play::serverbound::chat_command_signed::DESCRIPTOR,
    play::serverbound::chat::DESCRIPTOR,
    play::serverbound::chat_session_update::DESCRIPTOR,
    play::serverbound::chunk_batch_received::DESCRIPTOR,
    play::serverbound::client_command::DESCRIPTOR,
    play::serverbound::client_tick_end::DESCRIPTOR,
    play::serverbound::client_information::DESCRIPTOR,
    play::serverbound::command_suggestion::DESCRIPTOR,
    play::serverbound::configuration_acknowledged::DESCRIPTOR,
    play::serverbound::container_button_click::DESCRIPTOR,
    play::serverbound::container_click::DESCRIPTOR,
    play::serverbound::container_close::DESCRIPTOR,
    play::serverbound::container_slot_state_changed::DESCRIPTOR,
    play::serverbound::cookie_response::DESCRIPTOR,
    play::serverbound::custom_payload::DESCRIPTOR,
    play::serverbound::debug_subscription_request::DESCRIPTOR,
    play::serverbound::edit_book::DESCRIPTOR,
    play::serverbound::entity_tag_query::DESCRIPTOR,
    play::serverbound::interact::DESCRIPTOR,
    play::serverbound::jigsaw_generate::DESCRIPTOR,
    play::serverbound::keep_alive::DESCRIPTOR,
    play::serverbound::lock_difficulty::DESCRIPTOR,
    play::serverbound::move_player_pos::DESCRIPTOR,
    play::serverbound::move_player_pos_rot::DESCRIPTOR,
    play::serverbound::move_player_rot::DESCRIPTOR,
    play::serverbound::move_player_status_only::DESCRIPTOR,
    play::serverbound::move_vehicle::DESCRIPTOR,
    play::serverbound::paddle_boat::DESCRIPTOR,
    play::serverbound::pick_item_from_block::DESCRIPTOR,
    play::serverbound::pick_item_from_entity::DESCRIPTOR,
    play::serverbound::ping_request::DESCRIPTOR,
    play::serverbound::place_recipe::DESCRIPTOR,
    play::serverbound::player_abilities::DESCRIPTOR,
    play::serverbound::player_action::DESCRIPTOR,
    play::serverbound::player_command::DESCRIPTOR,
    play::serverbound::player_input::DESCRIPTOR,
    play::serverbound::player_loaded::DESCRIPTOR,
    play::serverbound::pong::DESCRIPTOR,
    play::serverbound::punch::DESCRIPTOR,
    play::serverbound::recipe_book_change_settings::DESCRIPTOR,
    play::serverbound::recipe_book_seen_recipe::DESCRIPTOR,
    play::serverbound::rename_item::DESCRIPTOR,
    play::serverbound::resource_pack::DESCRIPTOR,
    play::serverbound::seen_advancements::DESCRIPTOR,
    play::serverbound::select_trade::DESCRIPTOR,
    play::serverbound::set_beacon::DESCRIPTOR,
    play::serverbound::set_carried_item::DESCRIPTOR,
    play::serverbound::set_command_block::DESCRIPTOR,
    play::serverbound::set_command_minecart::DESCRIPTOR,
    play::serverbound::set_creative_mode_slot::DESCRIPTOR,
    play::serverbound::set_game_rule::DESCRIPTOR,
    play::serverbound::set_jigsaw_block::DESCRIPTOR,
    play::serverbound::set_structure_block::DESCRIPTOR,
    play::serverbound::set_test_block::DESCRIPTOR,
    play::serverbound::sign_update::DESCRIPTOR,
    play::serverbound::spectator_action::DESCRIPTOR,
    play::serverbound::teleport_to_entity::DESCRIPTOR,
    play::serverbound::test_instance_block_action::DESCRIPTOR,
    play::serverbound::use_item_on::DESCRIPTOR,
    play::serverbound::use_item::DESCRIPTOR,
    play::serverbound::custom_click_action::DESCRIPTOR,
];

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn inventory_is_complete_and_state_direction_ids_are_unique() {
        assert_eq!(PACKETS.len(), 260);
        let mut keys = std::collections::HashSet::new();
        for packet in PACKETS {
            assert!(keys.insert((packet.state, packet.direction, packet.id)));
            assert!(!packet.official_name.is_empty());
        }
        for (state, direction, count) in [
            (State::Handshaking, Direction::Serverbound, 1),
            (State::Status, Direction::Clientbound, 2),
            (State::Status, Direction::Serverbound, 2),
            (State::Login, Direction::Clientbound, 6),
            (State::Login, Direction::Serverbound, 5),
            (State::Configuration, Direction::Clientbound, 21),
            (State::Configuration, Direction::Serverbound, 10),
            (State::Play, Direction::Clientbound, 144),
            (State::Play, Direction::Serverbound, 69),
        ] {
            let ids: Vec<_> = PACKETS
                .iter()
                .filter(|p| p.state == state && p.direction == direction)
                .map(|p| p.id)
                .collect();
            assert_eq!(ids, (0..count).collect::<Vec<_>>());
        }
        assert_eq!(play::serverbound::set_carried_item::ID, 0x36);
        assert_eq!(handshaking::serverbound::legacy_server_list_ping::ID, 0xFE);
    }
}
