const views = [...document.querySelectorAll(".view")];
const navItems = [...document.querySelectorAll("[data-view]")];
const titles = { overview: "Control plane overview", projects: "Projects", builds: "Build pipeline", deployments: "Runtime graph", metrics: "Runtime metrics", admin: "System specification" };
const api = async (path, options = {}) => { const response = await fetch(path, { credentials: "include", cache: "no-store", ...options, headers: { ...(options.body ? { "content-type": "application/json" } : {}), ...(options.headers || {}) } }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error || `request failed (${response.status})`); return body; };
let authMode = "signin";
const renderAuthMode = () => { const signup = authMode === "signup"; document.querySelector("#auth-title").textContent = signup ? "Create your local control-plane account." : "Sign in to your control plane."; document.querySelector("#auth-copy").textContent = signup ? "Start with a bounded local account. Admin access is granted separately." : "Use your Janus account to inspect projects, lifecycle state, and admin evidence."; document.querySelector("#auth-name-field").hidden = !signup; document.querySelector("#auth-name").required = signup; document.querySelector("#auth-password").autocomplete = signup ? "new-password" : "current-password"; document.querySelector("#auth-submit").innerHTML = signup ? "Create account <span>→</span>" : "Sign in <span>→</span>"; document.querySelector("#auth-switch").textContent = signup ? "Already have an account? Sign in" : "Need an account? Sign up"; document.querySelector("#auth-foot").textContent = signup ? "Your account is created locally. Admin permissions remain explicitly granted." : "New here? Create a local account in a few seconds."; };
const setView = (name) => { views.forEach((view) => view.classList.toggle("active-view", view.id === `view-${name}`)); navItems.forEach((item) => item.classList.toggle("active", item.dataset.view === name)); document.querySelector("#page-title").textContent = titles[name] || titles.overview; document.querySelector("#breadcrumb").textContent = (name || "overview").toUpperCase(); window.history.replaceState({}, "", name === "overview" ? "/" : `/?view=${name}`); document.querySelector("#sidebar").classList.remove("open"); };
navItems.forEach((item) => item.addEventListener("click", () => setView(item.dataset.view)));
document.querySelector("#mobile-menu").addEventListener("click", () => document.querySelector("#sidebar").classList.toggle("open"));
const statusClass = (value) => { const normalized = String(value || "unknown").toLowerCase(); return ["succeeded", "running", "built", "ready", "active"].includes(normalized) ? "good" : ["failed", "error", "dead_lettered"].includes(normalized) ? "warn" : "neutral"; };
const resourceRow = (title, meta, status) => `<div class="resource-row"><div><div class="resource-title">${escapeHtml(title)}</div><div class="resource-meta">${escapeHtml(meta)}</div></div><span class="status-badge ${statusClass(status)}">${escapeHtml(status || "unknown")}</span><span class="resource-meta">updated locally</span></div>`;
const escapeHtml = (value) => String(value ?? "").replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" }[char]));
const renderList = (id, items, empty, map) => { const target = document.querySelector(`#${id}`); target.innerHTML = items.length ? items.map(map).join("") : `<div class="empty-state">${empty}</div>`; };
async function loadResources() { try { const [projects, builds, deployments, health] = await Promise.all([api("/api/v1/projects"), api("/api/v1/builds"), api("/api/v1/deployments"), api("/healthz")]); const projectItems = projects.projects || []; const buildItems = builds.builds || []; const deploymentItems = deployments.deployments || []; document.querySelector("#metric-projects").textContent = projectItems.length; document.querySelector("#metric-builds").textContent = buildItems.length; document.querySelector("#metric-deployments").textContent = deploymentItems.length; document.querySelector("#metric-verification").textContent = health.status === "ok" ? "PASS" : "CHECK"; document.querySelector("#system-status").textContent = health.status === "ok" ? "System healthy" : "System check"; document.querySelector("#projects-count").textContent = `${projectItems.length} project${projectItems.length === 1 ? "" : "s"}`; document.querySelector("#builds-count").textContent = `${buildItems.length} build record${buildItems.length === 1 ? "" : "s"}`; document.querySelector("#deployments-count").textContent = `${deploymentItems.length} deployment${deploymentItems.length === 1 ? "" : "s"}`; renderList("projects-list", projectItems, "No projects in this tenant yet.", (item) => resourceRow(item.name || item.slug || `Project ${item.id}`, `${item.repoProvider || "repository"} · ${item.repoBranch || "default branch"}`, item.status)); renderList("builds-list", buildItems, "No builds have been submitted yet.", (item) => resourceRow(item.id, `${item.sourceRef || "source"} · ${item.artifactRuntime || "artifact pending"}`, item.status)); renderList("deployments-list", deploymentItems, "No deployments have been created yet.", (item) => resourceRow(item.id, `${item.runtimeMode || "runtime"} · ${item.runtimeEndpoint || "endpoint pending"}`, item.status)); } catch (error) { document.querySelector("#system-status").textContent = "Sign in required"; } }
async function loadSpec() { const response = await fetch(`/api/v1/admin/spec?session=${Date.now()}`, { credentials: "include", cache: "no-store" }); if (!response.ok) throw new Error(`spec request failed (${response.status})`); const source = await response.text(); const documentSource = new DOMParser().parseFromString(source, "text/html"); document.querySelectorAll("style[data-spec-style]").forEach((style) => style.remove()); documentSource.querySelectorAll("head style").forEach((style) => { const scopedStyle = document.createElement("style"); scopedStyle.dataset.specStyle = "true"; scopedStyle.textContent = `@scope (#spec-content) { ${style.textContent} }`; document.head.appendChild(scopedStyle); }); const target = document.querySelector("#spec-content"); target.replaceChildren(...[...documentSource.body.children].map((child) => child.cloneNode(true))); target.hidden = false; target.querySelectorAll("script").forEach((script) => { if (script.type === "application/json") return; const executable = document.createElement("script"); executable.textContent = script.textContent; script.replaceWith(executable); }); }
async function loadSession() { try { const payload = await api("/api/v1/auth/me"); const user = payload.user || {}; document.querySelector("#user-pill").textContent = user.email || "Signed in"; document.querySelector("#sign-out").hidden = false; document.querySelector("#auth-overlay").hidden = true; const canView = ((Number(user.permissions) || 0) & 32) !== 0; document.querySelector("#spec-content").hidden = !canView; document.querySelector("#admin-gate").hidden = canView; if (canView) await loadSpec(); await loadResources(); if (new URLSearchParams(window.location.search).get("view") === "metrics") await loadMetrics(); } catch { document.querySelector("#auth-overlay").hidden = false; document.querySelector("#spec-content").hidden = true; document.querySelector("#admin-gate").hidden = false; } }
document.querySelector("#auth-switch").addEventListener("click", () => { authMode = authMode === "signin" ? "signup" : "signin"; document.querySelector("#auth-error").hidden = true; renderAuthMode(); });
document.querySelector("#auth-form").addEventListener("submit", async (event) => { event.preventDefault(); const error = document.querySelector("#auth-error"); error.hidden = true; const email = document.querySelector("#auth-email").value.trim(); const password = document.querySelector("#auth-password").value; try { if (authMode === "signup") { await api("/api/v1/auth/signup", { method: "POST", body: JSON.stringify({ email, password, name: document.querySelector("#auth-name").value.trim() }) }); } await api("/api/v1/auth/signin", { method: "POST", body: JSON.stringify({ email, password }) }); await loadSession(); } catch (reason) { error.textContent = reason.message; error.hidden = false; } });
document.querySelector("#sign-out").addEventListener("click", async () => { await fetch("/api/v1/auth/signout", { method: "POST", credentials: "include" }); window.location.reload(); });
["projects", "builds", "deployments"].forEach((name) => document.querySelector(`#refresh-${name}`).addEventListener("click", loadResources));
let metricsTimer;
const renderMetrics = (snapshot) => { const { health, ready, projects, builds, deployments, runners, telemetry, raw } = snapshot; const projectItems = projects.projects || []; const buildItems = builds.builds || []; const deploymentItems = deployments.deployments || []; const runnerItems = runners.runners || []; const samples = telemetry.metrics || []; const runningRunners = runnerItems.filter((item) => ["active", "ready", "leased"].includes(String(item.state).toLowerCase())).length; document.querySelector("#live-system").textContent = health.status === "ok" && ready.status === "ready" ? "READY" : "CHECK"; document.querySelector("#live-system-detail").textContent = `${health.status} · ${ready.status}`; document.querySelector("#live-projects").textContent = projectItems.length; document.querySelector("#live-builds").textContent = buildItems.length; document.querySelector("#live-deployments").textContent = deploymentItems.length; document.querySelector("#live-runners").textContent = runnerItems.length; document.querySelector("#live-runners-detail").textContent = `${runningRunners} active · ${runnerItems.length} registered`; document.querySelector("#live-samples").textContent = samples.length; document.querySelector("#metrics-updated").textContent = `Updated ${new Date().toLocaleTimeString()}`; const values = [["Projects", projectItems.length], ["Builds", buildItems.length], ["Deployments", deploymentItems.length], ["Runners", runnerItems.length], ["Telemetry", samples.length]]; const max = Math.max(1, ...values.map(([, value]) => value)); document.querySelector("#metrics-bars").innerHTML = values.map(([label, value]) => `<div class="metrics-bar-row"><span>${label}</span><div class="metrics-bar-track"><div class="metrics-bar-fill" style="width:${Math.max(value ? 4 : 0, (value / max) * 100)}%"></div></div><strong>${value}</strong></div>`).join(""); document.querySelector("#metrics-samples").innerHTML = samples.length ? samples.map((sample) => `<div class="metrics-sample-row"><div><strong>${escapeHtml(sample.name)}</strong><small>${escapeHtml(sample.kind)} · ${new Date(Number(sample.timestamp || 0) * 1000).toLocaleTimeString()}</small></div><strong>${Number(sample.value).toLocaleString()}</strong></div>`).join("") : '<div class="metrics-empty">No telemetry samples have been recorded in the bounded buffer yet.</div>'; document.querySelector("#metrics-raw-output").textContent = raw || "No Prometheus samples currently available."; };
const loadMetrics = async () => { try { const [health, ready, projects, builds, deployments, runners, telemetry, rawResponse] = await Promise.all([api("/healthz"), api("/readyz"), api("/api/v1/projects"), api("/api/v1/builds"), api("/api/v1/deployments"), api("/api/v1/runners"), api("/api/v1/telemetry"), fetch(`/metrics?ts=${Date.now()}`, { credentials: "include", cache: "no-store" }).then((response) => response.text())]); renderMetrics({ health, ready, projects, builds, deployments, runners, telemetry, raw: rawResponse }); } catch (error) { document.querySelector("#metrics-updated").textContent = error.message; } };
document.querySelector("#refresh-metrics").addEventListener("click", loadMetrics);
const queryView = new URLSearchParams(window.location.search).get("view"); setView(titles[queryView] ? queryView : "overview"); loadSession();
document.querySelectorAll('[data-view="metrics"]').forEach((item) => item.addEventListener("click", () => { loadMetrics(); clearInterval(metricsTimer); metricsTimer = setInterval(loadMetrics, 5000); }));
